// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cell_state_type::CellState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cell_state`.
///
/// Obtain a handle from the [`CellStateTableAccess::cell_state`] method on [`super::RemoteTables`],
/// like `ctx.db.cell_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell_state().on_insert(...)`.
pub struct CellStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<CellState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cell_state`.
pub struct CellStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CellStateTableAccessor {
    type Row = CellState;
    type Handle<'db> = CellStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cell_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cell_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CellStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CellStateTableHandle`], which mediates access to the table `cell_state`.
    fn cell_state(&self) -> CellStateTableHandle<'_>;
}

impl CellStateTableAccess for super::RemoteTables {
    fn cell_state(&self) -> CellStateTableHandle<'_> {
        CellStateTableHandle {
            imp: self.imp.get_table::<CellState>("cell_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CellStateInsertCallbackId(__sdk::CallbackId);
pub struct CellStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CellStateTableHandle<'ctx> {
    type Row = CellState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CellState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CellStateTableHandle<'ctx> {
    type Row = CellState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CellState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CellStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellStateInsertCallbackId {
        CellStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CellStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CellStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellStateDeleteCallbackId {
        CellStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CellStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CellStateTableHandle<'ctx> {
    type InsertCallbackId = CellStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellStateInsertCallbackId {
        CellStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CellStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CellStateTableHandle<'ctx> {
    type DeleteCallbackId = CellStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellStateDeleteCallbackId {
        CellStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CellStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CellStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CellStateTableHandle<'ctx> {
    type UpdateCallbackId = CellStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CellStateUpdateCallbackId {
        CellStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CellStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CellStateTableHandle<'ctx> {
    type UpdateCallbackId = CellStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CellStateUpdateCallbackId {
        CellStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CellStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `cell_id` unique index on the table `cell_state`,
/// which allows point queries on the field of the same name
/// via the [`CellStateCellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell_state().cell_id().find(...)`.
pub struct CellStateCellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CellState, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CellStateTableHandle<'ctx> {
    /// Get a handle on the `cell_id` unique index on the table `cell_state`.
    pub fn cell_id(&self) -> CellStateCellIdUnique<'ctx> {
        CellStateCellIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("cell_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CellStateCellIdUnique<'ctx> {
    /// Find the subscribed row whose `cell_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<CellState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CellState>("cell_state");
    _table.add_unique_constraint::<u32>("cell_id", |row| &row.cell_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CellState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CellState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CellState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cell_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CellState`.
    fn cell_state(&self) -> __sdk::__query_builder::Table<CellState>;
}

impl cell_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn cell_state(&self) -> __sdk::__query_builder::Table<CellState> {
        __sdk::__query_builder::Table::new("cell_state")
    }
}
