// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::terrain_class_type::TerrainClass;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CellTerrain {
    pub cell_id: u32,
    pub q: i32,
    pub r: i32,
    pub chunk_q: i16,
    pub chunk_r: i16,
    pub terrain: TerrainClass,
    pub elevation: i16,
    pub passable: bool,
    pub capturable: bool,
    pub habitable: bool,
}

impl __sdk::InModule for CellTerrain {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CellTerrain`.
///
/// Provides typed access to columns for query building.
pub struct CellTerrainCols {
    pub cell_id: __sdk::__query_builder::Col<CellTerrain, u32>,
    pub q: __sdk::__query_builder::Col<CellTerrain, i32>,
    pub r: __sdk::__query_builder::Col<CellTerrain, i32>,
    pub chunk_q: __sdk::__query_builder::Col<CellTerrain, i16>,
    pub chunk_r: __sdk::__query_builder::Col<CellTerrain, i16>,
    pub terrain: __sdk::__query_builder::Col<CellTerrain, TerrainClass>,
    pub elevation: __sdk::__query_builder::Col<CellTerrain, i16>,
    pub passable: __sdk::__query_builder::Col<CellTerrain, bool>,
    pub capturable: __sdk::__query_builder::Col<CellTerrain, bool>,
    pub habitable: __sdk::__query_builder::Col<CellTerrain, bool>,
}

impl __sdk::__query_builder::HasCols for CellTerrain {
    type Cols = CellTerrainCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CellTerrainCols {
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            q: __sdk::__query_builder::Col::new(table_name, "q"),
            r: __sdk::__query_builder::Col::new(table_name, "r"),
            chunk_q: __sdk::__query_builder::Col::new(table_name, "chunk_q"),
            chunk_r: __sdk::__query_builder::Col::new(table_name, "chunk_r"),
            terrain: __sdk::__query_builder::Col::new(table_name, "terrain"),
            elevation: __sdk::__query_builder::Col::new(table_name, "elevation"),
            passable: __sdk::__query_builder::Col::new(table_name, "passable"),
            capturable: __sdk::__query_builder::Col::new(table_name, "capturable"),
            habitable: __sdk::__query_builder::Col::new(table_name, "habitable"),
        }
    }
}

/// Indexed column accessor struct for the table `CellTerrain`.
///
/// Provides typed access to indexed columns for query building.
pub struct CellTerrainIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<CellTerrain, u32>,
}

impl __sdk::__query_builder::HasIxCols for CellTerrain {
    type IxCols = CellTerrainIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CellTerrainIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CellTerrain {}
