// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CellState {
    pub cell_id: u32,
    pub owner_player_id: u16,
    pub civilians: u64,
    pub civilian_capacity: u64,
    pub infantry: u64,
    pub military_capacity: u64,
    pub population_shard: u16,
    pub chunk_q: i16,
    pub chunk_r: i16,
    pub last_changed_step: u64,
}

impl __sdk::InModule for CellState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CellState`.
///
/// Provides typed access to columns for query building.
pub struct CellStateCols {
    pub cell_id: __sdk::__query_builder::Col<CellState, u32>,
    pub owner_player_id: __sdk::__query_builder::Col<CellState, u16>,
    pub civilians: __sdk::__query_builder::Col<CellState, u64>,
    pub civilian_capacity: __sdk::__query_builder::Col<CellState, u64>,
    pub infantry: __sdk::__query_builder::Col<CellState, u64>,
    pub military_capacity: __sdk::__query_builder::Col<CellState, u64>,
    pub population_shard: __sdk::__query_builder::Col<CellState, u16>,
    pub chunk_q: __sdk::__query_builder::Col<CellState, i16>,
    pub chunk_r: __sdk::__query_builder::Col<CellState, i16>,
    pub last_changed_step: __sdk::__query_builder::Col<CellState, u64>,
}

impl __sdk::__query_builder::HasCols for CellState {
    type Cols = CellStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CellStateCols {
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            owner_player_id: __sdk::__query_builder::Col::new(table_name, "owner_player_id"),
            civilians: __sdk::__query_builder::Col::new(table_name, "civilians"),
            civilian_capacity: __sdk::__query_builder::Col::new(table_name, "civilian_capacity"),
            infantry: __sdk::__query_builder::Col::new(table_name, "infantry"),
            military_capacity: __sdk::__query_builder::Col::new(table_name, "military_capacity"),
            population_shard: __sdk::__query_builder::Col::new(table_name, "population_shard"),
            chunk_q: __sdk::__query_builder::Col::new(table_name, "chunk_q"),
            chunk_r: __sdk::__query_builder::Col::new(table_name, "chunk_r"),
            last_changed_step: __sdk::__query_builder::Col::new(table_name, "last_changed_step"),
        }
    }
}

/// Indexed column accessor struct for the table `CellState`.
///
/// Provides typed access to indexed columns for query building.
pub struct CellStateIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<CellState, u32>,
    pub owner_player_id: __sdk::__query_builder::IxCol<CellState, u16>,
    pub population_shard: __sdk::__query_builder::IxCol<CellState, u16>,
}

impl __sdk::__query_builder::HasIxCols for CellState {
    type IxCols = CellStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CellStateIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
            owner_player_id: __sdk::__query_builder::IxCol::new(table_name, "owner_player_id"),
            population_shard: __sdk::__query_builder::IxCol::new(table_name, "population_shard"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CellState {}
