// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::cluster_policy_kind_type::ClusterPolicyKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClusterPolicyAssignment {
    pub cell_id: u32,
    pub owner_player_id: u8,
    pub kind: ClusterPolicyKind,
    pub orientation_q: i32,
    pub orientation_r: i32,
    pub revision: u64,
}

impl __sdk::InModule for ClusterPolicyAssignment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClusterPolicyAssignment`.
///
/// Provides typed access to columns for query building.
pub struct ClusterPolicyAssignmentCols {
    pub cell_id: __sdk::__query_builder::Col<ClusterPolicyAssignment, u32>,
    pub owner_player_id: __sdk::__query_builder::Col<ClusterPolicyAssignment, u8>,
    pub kind: __sdk::__query_builder::Col<ClusterPolicyAssignment, ClusterPolicyKind>,
    pub orientation_q: __sdk::__query_builder::Col<ClusterPolicyAssignment, i32>,
    pub orientation_r: __sdk::__query_builder::Col<ClusterPolicyAssignment, i32>,
    pub revision: __sdk::__query_builder::Col<ClusterPolicyAssignment, u64>,
}

impl __sdk::__query_builder::HasCols for ClusterPolicyAssignment {
    type Cols = ClusterPolicyAssignmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClusterPolicyAssignmentCols {
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            owner_player_id: __sdk::__query_builder::Col::new(table_name, "owner_player_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            orientation_q: __sdk::__query_builder::Col::new(table_name, "orientation_q"),
            orientation_r: __sdk::__query_builder::Col::new(table_name, "orientation_r"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `ClusterPolicyAssignment`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClusterPolicyAssignmentIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<ClusterPolicyAssignment, u32>,
    pub owner_player_id: __sdk::__query_builder::IxCol<ClusterPolicyAssignment, u8>,
}

impl __sdk::__query_builder::HasIxCols for ClusterPolicyAssignment {
    type IxCols = ClusterPolicyAssignmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClusterPolicyAssignmentIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
            owner_player_id: __sdk::__query_builder::IxCol::new(table_name, "owner_player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClusterPolicyAssignment {}
