// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cluster_policy_assignment_type::ClusterPolicyAssignment;
use super::cluster_policy_kind_type::ClusterPolicyKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cluster_policy_assignment`.
///
/// Obtain a handle from the [`ClusterPolicyAssignmentTableAccess::cluster_policy_assignment`] method on [`super::RemoteTables`],
/// like `ctx.db.cluster_policy_assignment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cluster_policy_assignment().on_insert(...)`.
pub struct ClusterPolicyAssignmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClusterPolicyAssignment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cluster_policy_assignment`.
pub struct ClusterPolicyAssignmentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ClusterPolicyAssignmentTableAccessor {
    type Row = ClusterPolicyAssignment;
    type Handle<'db> = ClusterPolicyAssignmentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cluster_policy_assignment()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cluster_policy_assignment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClusterPolicyAssignmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClusterPolicyAssignmentTableHandle`], which mediates access to the table `cluster_policy_assignment`.
    fn cluster_policy_assignment(&self) -> ClusterPolicyAssignmentTableHandle<'_>;
}

impl ClusterPolicyAssignmentTableAccess for super::RemoteTables {
    fn cluster_policy_assignment(&self) -> ClusterPolicyAssignmentTableHandle<'_> {
        ClusterPolicyAssignmentTableHandle {
            imp: self
                .imp
                .get_table::<ClusterPolicyAssignment>("cluster_policy_assignment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClusterPolicyAssignmentInsertCallbackId(__sdk::CallbackId);
pub struct ClusterPolicyAssignmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ClusterPolicyAssignmentTableHandle<'ctx> {
    type Row = ClusterPolicyAssignment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClusterPolicyAssignment> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ClusterPolicyAssignmentTableHandle<'ctx> {
    type Row = ClusterPolicyAssignment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClusterPolicyAssignment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClusterPolicyAssignmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentInsertCallbackId {
        ClusterPolicyAssignmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClusterPolicyAssignmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClusterPolicyAssignmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentDeleteCallbackId {
        ClusterPolicyAssignmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClusterPolicyAssignmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ClusterPolicyAssignmentTableHandle<'ctx> {
    type InsertCallbackId = ClusterPolicyAssignmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentInsertCallbackId {
        ClusterPolicyAssignmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClusterPolicyAssignmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ClusterPolicyAssignmentTableHandle<'ctx> {
    type DeleteCallbackId = ClusterPolicyAssignmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentDeleteCallbackId {
        ClusterPolicyAssignmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClusterPolicyAssignmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClusterPolicyAssignmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClusterPolicyAssignmentTableHandle<'ctx> {
    type UpdateCallbackId = ClusterPolicyAssignmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentUpdateCallbackId {
        ClusterPolicyAssignmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClusterPolicyAssignmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ClusterPolicyAssignmentTableHandle<'ctx> {
    type UpdateCallbackId = ClusterPolicyAssignmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClusterPolicyAssignmentUpdateCallbackId {
        ClusterPolicyAssignmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClusterPolicyAssignmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `cell_id` unique index on the table `cluster_policy_assignment`,
/// which allows point queries on the field of the same name
/// via the [`ClusterPolicyAssignmentCellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cluster_policy_assignment().cell_id().find(...)`.
pub struct ClusterPolicyAssignmentCellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ClusterPolicyAssignment, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClusterPolicyAssignmentTableHandle<'ctx> {
    /// Get a handle on the `cell_id` unique index on the table `cluster_policy_assignment`.
    pub fn cell_id(&self) -> ClusterPolicyAssignmentCellIdUnique<'ctx> {
        ClusterPolicyAssignmentCellIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("cell_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClusterPolicyAssignmentCellIdUnique<'ctx> {
    /// Find the subscribed row whose `cell_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<ClusterPolicyAssignment> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<ClusterPolicyAssignment>("cluster_policy_assignment");
    _table.add_unique_constraint::<u32>("cell_id", |row| &row.cell_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClusterPolicyAssignment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClusterPolicyAssignment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClusterPolicyAssignment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cluster_policy_assignmentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClusterPolicyAssignment`.
    fn cluster_policy_assignment(&self) -> __sdk::__query_builder::Table<ClusterPolicyAssignment>;
}

impl cluster_policy_assignmentQueryTableAccess for __sdk::QueryTableAccessor {
    fn cluster_policy_assignment(&self) -> __sdk::__query_builder::Table<ClusterPolicyAssignment> {
        __sdk::__query_builder::Table::new("cluster_policy_assignment")
    }
}
