// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::combat_front_type::CombatFront;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `combat_front`.
///
/// Obtain a handle from the [`CombatFrontTableAccess::combat_front`] method on [`super::RemoteTables`],
/// like `ctx.db.combat_front()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_front().on_insert(...)`.
pub struct CombatFrontTableHandle<'ctx> {
    imp: __sdk::TableHandle<CombatFront>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `combat_front`.
pub struct CombatFrontTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CombatFrontTableAccessor {
    type Row = CombatFront;
    type Handle<'db> = CombatFrontTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.combat_front()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `combat_front`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CombatFrontTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CombatFrontTableHandle`], which mediates access to the table `combat_front`.
    fn combat_front(&self) -> CombatFrontTableHandle<'_>;
}

impl CombatFrontTableAccess for super::RemoteTables {
    fn combat_front(&self) -> CombatFrontTableHandle<'_> {
        CombatFrontTableHandle {
            imp: self.imp.get_table::<CombatFront>("combat_front"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CombatFrontInsertCallbackId(__sdk::CallbackId);
pub struct CombatFrontDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CombatFrontTableHandle<'ctx> {
    type Row = CombatFront;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CombatFront> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CombatFrontTableHandle<'ctx> {
    type Row = CombatFront;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CombatFront> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CombatFrontInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatFrontInsertCallbackId {
        CombatFrontInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatFrontInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CombatFrontDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatFrontDeleteCallbackId {
        CombatFrontDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatFrontDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CombatFrontTableHandle<'ctx> {
    type InsertCallbackId = CombatFrontInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatFrontInsertCallbackId {
        CombatFrontInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CombatFrontInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CombatFrontTableHandle<'ctx> {
    type DeleteCallbackId = CombatFrontDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CombatFrontDeleteCallbackId {
        CombatFrontDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CombatFrontDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CombatFrontUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CombatFrontTableHandle<'ctx> {
    type UpdateCallbackId = CombatFrontUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatFrontUpdateCallbackId {
        CombatFrontUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatFrontUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CombatFrontTableHandle<'ctx> {
    type UpdateCallbackId = CombatFrontUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CombatFrontUpdateCallbackId {
        CombatFrontUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CombatFrontUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `front_key` unique index on the table `combat_front`,
/// which allows point queries on the field of the same name
/// via the [`CombatFrontFrontKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.combat_front().front_key().find(...)`.
pub struct CombatFrontFrontKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CombatFront, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CombatFrontTableHandle<'ctx> {
    /// Get a handle on the `front_key` unique index on the table `combat_front`.
    pub fn front_key(&self) -> CombatFrontFrontKeyUnique<'ctx> {
        CombatFrontFrontKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("front_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CombatFrontFrontKeyUnique<'ctx> {
    /// Find the subscribed row whose `front_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CombatFront> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CombatFront>("combat_front");
    _table.add_unique_constraint::<String>("front_key", |row| &row.front_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CombatFront>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CombatFront>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CombatFront`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait combat_frontQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CombatFront`.
    fn combat_front(&self) -> __sdk::__query_builder::Table<CombatFront>;
}

impl combat_frontQueryTableAccess for __sdk::QueryTableAccessor {
    fn combat_front(&self) -> __sdk::__query_builder::Table<CombatFront> {
        __sdk::__query_builder::Table::new("combat_front")
    }
}
