// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatFront {
    pub front_key: String,
    pub attacker_player_id: u16,
    pub defender_player_id: u16,
    pub from_cell: u32,
    pub to_cell: u32,
    pub queued_infantry: u64,
    pub attacker_engaged: u64,
    pub defender_engaged: u64,
    pub attacker_casualties: u64,
    pub defender_casualties: u64,
    pub frontage: u64,
    pub uphill: bool,
    pub logical_step: u64,
}

impl __sdk::InModule for CombatFront {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CombatFront`.
///
/// Provides typed access to columns for query building.
pub struct CombatFrontCols {
    pub front_key: __sdk::__query_builder::Col<CombatFront, String>,
    pub attacker_player_id: __sdk::__query_builder::Col<CombatFront, u16>,
    pub defender_player_id: __sdk::__query_builder::Col<CombatFront, u16>,
    pub from_cell: __sdk::__query_builder::Col<CombatFront, u32>,
    pub to_cell: __sdk::__query_builder::Col<CombatFront, u32>,
    pub queued_infantry: __sdk::__query_builder::Col<CombatFront, u64>,
    pub attacker_engaged: __sdk::__query_builder::Col<CombatFront, u64>,
    pub defender_engaged: __sdk::__query_builder::Col<CombatFront, u64>,
    pub attacker_casualties: __sdk::__query_builder::Col<CombatFront, u64>,
    pub defender_casualties: __sdk::__query_builder::Col<CombatFront, u64>,
    pub frontage: __sdk::__query_builder::Col<CombatFront, u64>,
    pub uphill: __sdk::__query_builder::Col<CombatFront, bool>,
    pub logical_step: __sdk::__query_builder::Col<CombatFront, u64>,
}

impl __sdk::__query_builder::HasCols for CombatFront {
    type Cols = CombatFrontCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatFrontCols {
            front_key: __sdk::__query_builder::Col::new(table_name, "front_key"),
            attacker_player_id: __sdk::__query_builder::Col::new(table_name, "attacker_player_id"),
            defender_player_id: __sdk::__query_builder::Col::new(table_name, "defender_player_id"),
            from_cell: __sdk::__query_builder::Col::new(table_name, "from_cell"),
            to_cell: __sdk::__query_builder::Col::new(table_name, "to_cell"),
            queued_infantry: __sdk::__query_builder::Col::new(table_name, "queued_infantry"),
            attacker_engaged: __sdk::__query_builder::Col::new(table_name, "attacker_engaged"),
            defender_engaged: __sdk::__query_builder::Col::new(table_name, "defender_engaged"),
            attacker_casualties: __sdk::__query_builder::Col::new(
                table_name,
                "attacker_casualties",
            ),
            defender_casualties: __sdk::__query_builder::Col::new(
                table_name,
                "defender_casualties",
            ),
            frontage: __sdk::__query_builder::Col::new(table_name, "frontage"),
            uphill: __sdk::__query_builder::Col::new(table_name, "uphill"),
            logical_step: __sdk::__query_builder::Col::new(table_name, "logical_step"),
        }
    }
}

/// Indexed column accessor struct for the table `CombatFront`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatFrontIxCols {
    pub attacker_player_id: __sdk::__query_builder::IxCol<CombatFront, u16>,
    pub defender_player_id: __sdk::__query_builder::IxCol<CombatFront, u16>,
    pub front_key: __sdk::__query_builder::IxCol<CombatFront, String>,
    pub to_cell: __sdk::__query_builder::IxCol<CombatFront, u32>,
}

impl __sdk::__query_builder::HasIxCols for CombatFront {
    type IxCols = CombatFrontIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatFrontIxCols {
            attacker_player_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "attacker_player_id",
            ),
            defender_player_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "defender_player_id",
            ),
            front_key: __sdk::__query_builder::IxCol::new(table_name, "front_key"),
            to_cell: __sdk::__query_builder::IxCol::new(table_name, "to_cell"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CombatFront {}
