// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CommandWatermark {
    pub player_id: u16,
    pub highest_client_command_id: u64,
}

impl __sdk::InModule for CommandWatermark {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CommandWatermark`.
///
/// Provides typed access to columns for query building.
pub struct CommandWatermarkCols {
    pub player_id: __sdk::__query_builder::Col<CommandWatermark, u16>,
    pub highest_client_command_id: __sdk::__query_builder::Col<CommandWatermark, u64>,
}

impl __sdk::__query_builder::HasCols for CommandWatermark {
    type Cols = CommandWatermarkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CommandWatermarkCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            highest_client_command_id: __sdk::__query_builder::Col::new(
                table_name,
                "highest_client_command_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `CommandWatermark`.
///
/// Provides typed access to indexed columns for query building.
pub struct CommandWatermarkIxCols {
    pub player_id: __sdk::__query_builder::IxCol<CommandWatermark, u16>,
}

impl __sdk::__query_builder::HasIxCols for CommandWatermark {
    type IxCols = CommandWatermarkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CommandWatermarkIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CommandWatermark {}
