// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::command_receipt_type::CommandReceipt;
use super::receipt_status_type::ReceiptStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `command_receipt`.
///
/// Obtain a handle from the [`CommandReceiptTableAccess::command_receipt`] method on [`super::RemoteTables`],
/// like `ctx.db.command_receipt()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.command_receipt().on_insert(...)`.
pub struct CommandReceiptTableHandle<'ctx> {
    imp: __sdk::TableHandle<CommandReceipt>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `command_receipt`.
pub struct CommandReceiptTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CommandReceiptTableAccessor {
    type Row = CommandReceipt;
    type Handle<'db> = CommandReceiptTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.command_receipt()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `command_receipt`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CommandReceiptTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CommandReceiptTableHandle`], which mediates access to the table `command_receipt`.
    fn command_receipt(&self) -> CommandReceiptTableHandle<'_>;
}

impl CommandReceiptTableAccess for super::RemoteTables {
    fn command_receipt(&self) -> CommandReceiptTableHandle<'_> {
        CommandReceiptTableHandle {
            imp: self.imp.get_table::<CommandReceipt>("command_receipt"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CommandReceiptInsertCallbackId(__sdk::CallbackId);
pub struct CommandReceiptDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CommandReceiptTableHandle<'ctx> {
    type Row = CommandReceipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CommandReceipt> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CommandReceiptTableHandle<'ctx> {
    type Row = CommandReceipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CommandReceipt> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CommandReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommandReceiptInsertCallbackId {
        CommandReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CommandReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CommandReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommandReceiptDeleteCallbackId {
        CommandReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CommandReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CommandReceiptTableHandle<'ctx> {
    type InsertCallbackId = CommandReceiptInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommandReceiptInsertCallbackId {
        CommandReceiptInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CommandReceiptInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CommandReceiptTableHandle<'ctx> {
    type DeleteCallbackId = CommandReceiptDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CommandReceiptDeleteCallbackId {
        CommandReceiptDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CommandReceiptDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CommandReceiptUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CommandReceiptTableHandle<'ctx> {
    type UpdateCallbackId = CommandReceiptUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CommandReceiptUpdateCallbackId {
        CommandReceiptUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CommandReceiptUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CommandReceiptTableHandle<'ctx> {
    type UpdateCallbackId = CommandReceiptUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CommandReceiptUpdateCallbackId {
        CommandReceiptUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CommandReceiptUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `receipt_key` unique index on the table `command_receipt`,
/// which allows point queries on the field of the same name
/// via the [`CommandReceiptReceiptKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.command_receipt().receipt_key().find(...)`.
pub struct CommandReceiptReceiptKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CommandReceipt, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CommandReceiptTableHandle<'ctx> {
    /// Get a handle on the `receipt_key` unique index on the table `command_receipt`.
    pub fn receipt_key(&self) -> CommandReceiptReceiptKeyUnique<'ctx> {
        CommandReceiptReceiptKeyUnique {
            imp: self.imp.get_unique_constraint::<u128>("receipt_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CommandReceiptReceiptKeyUnique<'ctx> {
    /// Find the subscribed row whose `receipt_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<CommandReceipt> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CommandReceipt>("command_receipt");
    _table.add_unique_constraint::<u128>("receipt_key", |row| &row.receipt_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CommandReceipt>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CommandReceipt>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CommandReceipt`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait command_receiptQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CommandReceipt`.
    fn command_receipt(&self) -> __sdk::__query_builder::Table<CommandReceipt>;
}

impl command_receiptQueryTableAccess for __sdk::QueryTableAccessor {
    fn command_receipt(&self) -> __sdk::__query_builder::Table<CommandReceipt> {
        __sdk::__query_builder::Table::new("command_receipt")
    }
}
