// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::receipt_status_type::ReceiptStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CommandReceipt {
    pub receipt_key: u128,
    pub player_id: u16,
    pub client_command_id: u64,
    pub command_name: String,
    pub status: ReceiptStatus,
    pub order_id: u64,
    pub message: String,
    pub logical_step: u64,
}

impl __sdk::InModule for CommandReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CommandReceipt`.
///
/// Provides typed access to columns for query building.
pub struct CommandReceiptCols {
    pub receipt_key: __sdk::__query_builder::Col<CommandReceipt, u128>,
    pub player_id: __sdk::__query_builder::Col<CommandReceipt, u16>,
    pub client_command_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub command_name: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub status: __sdk::__query_builder::Col<CommandReceipt, ReceiptStatus>,
    pub order_id: __sdk::__query_builder::Col<CommandReceipt, u64>,
    pub message: __sdk::__query_builder::Col<CommandReceipt, String>,
    pub logical_step: __sdk::__query_builder::Col<CommandReceipt, u64>,
}

impl __sdk::__query_builder::HasCols for CommandReceipt {
    type Cols = CommandReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CommandReceiptCols {
            receipt_key: __sdk::__query_builder::Col::new(table_name, "receipt_key"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            client_command_id: __sdk::__query_builder::Col::new(table_name, "client_command_id"),
            command_name: __sdk::__query_builder::Col::new(table_name, "command_name"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            logical_step: __sdk::__query_builder::Col::new(table_name, "logical_step"),
        }
    }
}

/// Indexed column accessor struct for the table `CommandReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct CommandReceiptIxCols {
    pub player_id: __sdk::__query_builder::IxCol<CommandReceipt, u16>,
    pub receipt_key: __sdk::__query_builder::IxCol<CommandReceipt, u128>,
}

impl __sdk::__query_builder::HasIxCols for CommandReceipt {
    type IxCols = CommandReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CommandReceiptIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            receipt_key: __sdk::__query_builder::IxCol::new(table_name, "receipt_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CommandReceipt {}
