// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::map_preset_type::MapPreset;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConfigureMapArgs {
    pub preset: MapPreset,
}

impl From<ConfigureMapArgs> for super::Reducer {
    fn from(args: ConfigureMapArgs) -> Self {
        Self::ConfigureMap {
            preset: args.preset,
        }
    }
}

impl __sdk::InModule for ConfigureMapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `configure_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait configure_map {
    /// Request that the remote module invoke the reducer `configure_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`configure_map:configure_map_then`] to run a callback after the reducer completes.
    fn configure_map(&self, preset: MapPreset) -> __sdk::Result<()> {
        self.configure_map_then(preset, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `configure_map` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn configure_map_then(
        &self,
        preset: MapPreset,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl configure_map for super::RemoteReducers {
    fn configure_map_then(
        &self,
        preset: MapPreset,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ConfigureMapArgs { preset }, callback)
    }
}
