// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugBreakOrderConservationArgs {
    pub order_id: u64,
}

impl From<DebugBreakOrderConservationArgs> for super::Reducer {
    fn from(args: DebugBreakOrderConservationArgs) -> Self {
        Self::DebugBreakOrderConservation {
            order_id: args.order_id,
        }
    }
}

impl __sdk::InModule for DebugBreakOrderConservationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug_break_order_conservation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug_break_order_conservation {
    /// Request that the remote module invoke the reducer `debug_break_order_conservation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`debug_break_order_conservation:debug_break_order_conservation_then`] to run a callback after the reducer completes.
    fn debug_break_order_conservation(&self, order_id: u64) -> __sdk::Result<()> {
        self.debug_break_order_conservation_then(order_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `debug_break_order_conservation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn debug_break_order_conservation_then(
        &self,
        order_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl debug_break_order_conservation for super::RemoteReducers {
    fn debug_break_order_conservation_then(
        &self,
        order_id: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DebugBreakOrderConservationArgs { order_id }, callback)
    }
}
