// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DebugHarness {
    pub singleton_id: u8,
    pub enabled: bool,
}

impl __sdk::InModule for DebugHarness {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DebugHarness`.
///
/// Provides typed access to columns for query building.
pub struct DebugHarnessCols {
    pub singleton_id: __sdk::__query_builder::Col<DebugHarness, u8>,
    pub enabled: __sdk::__query_builder::Col<DebugHarness, bool>,
}

impl __sdk::__query_builder::HasCols for DebugHarness {
    type Cols = DebugHarnessCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DebugHarnessCols {
            singleton_id: __sdk::__query_builder::Col::new(table_name, "singleton_id"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
        }
    }
}

/// Indexed column accessor struct for the table `DebugHarness`.
///
/// Provides typed access to indexed columns for query building.
pub struct DebugHarnessIxCols {
    pub singleton_id: __sdk::__query_builder::IxCol<DebugHarness, u8>,
}

impl __sdk::__query_builder::HasIxCols for DebugHarness {
    type IxCols = DebugHarnessIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DebugHarnessIxCols {
            singleton_id: __sdk::__query_builder::IxCol::new(table_name, "singleton_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DebugHarness {}
