// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExpansionWave {
    pub order_id: u64,
    pub selected_cells: Vec<u32>,
    pub outside_depths: Vec<u16>,
    pub split_cursors: Vec<u8>,
    pub focus_cell_id: Option<u32>,
    pub target_cells: Vec<u32>,
}

impl __sdk::InModule for ExpansionWave {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ExpansionWave`.
///
/// Provides typed access to columns for query building.
pub struct ExpansionWaveCols {
    pub order_id: __sdk::__query_builder::Col<ExpansionWave, u64>,
    pub selected_cells: __sdk::__query_builder::Col<ExpansionWave, Vec<u32>>,
    pub outside_depths: __sdk::__query_builder::Col<ExpansionWave, Vec<u16>>,
    pub split_cursors: __sdk::__query_builder::Col<ExpansionWave, Vec<u8>>,
    pub focus_cell_id: __sdk::__query_builder::Col<ExpansionWave, Option<u32>>,
    pub target_cells: __sdk::__query_builder::Col<ExpansionWave, Vec<u32>>,
}

impl __sdk::__query_builder::HasCols for ExpansionWave {
    type Cols = ExpansionWaveCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ExpansionWaveCols {
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            selected_cells: __sdk::__query_builder::Col::new(table_name, "selected_cells"),
            outside_depths: __sdk::__query_builder::Col::new(table_name, "outside_depths"),
            split_cursors: __sdk::__query_builder::Col::new(table_name, "split_cursors"),
            focus_cell_id: __sdk::__query_builder::Col::new(table_name, "focus_cell_id"),
            target_cells: __sdk::__query_builder::Col::new(table_name, "target_cells"),
        }
    }
}

/// Indexed column accessor struct for the table `ExpansionWave`.
///
/// Provides typed access to indexed columns for query building.
pub struct ExpansionWaveIxCols {
    pub order_id: __sdk::__query_builder::IxCol<ExpansionWave, u64>,
}

impl __sdk::__query_builder::HasIxCols for ExpansionWave {
    type IxCols = ExpansionWaveIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ExpansionWaveIxCols {
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ExpansionWave {}
