// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExpansionGarrisonDebt {
    pub cell_id: u32,
    pub owner_player_id: u8,
    pub remaining_infantry: u64,
}

impl __sdk::InModule for ExpansionGarrisonDebt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ExpansionGarrisonDebt`.
///
/// Provides typed access to columns for query building.
pub struct ExpansionGarrisonDebtCols {
    pub cell_id: __sdk::__query_builder::Col<ExpansionGarrisonDebt, u32>,
    pub owner_player_id: __sdk::__query_builder::Col<ExpansionGarrisonDebt, u8>,
    pub remaining_infantry: __sdk::__query_builder::Col<ExpansionGarrisonDebt, u64>,
}

impl __sdk::__query_builder::HasCols for ExpansionGarrisonDebt {
    type Cols = ExpansionGarrisonDebtCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ExpansionGarrisonDebtCols {
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            owner_player_id: __sdk::__query_builder::Col::new(table_name, "owner_player_id"),
            remaining_infantry: __sdk::__query_builder::Col::new(table_name, "remaining_infantry"),
        }
    }
}

/// Indexed column accessor struct for the table `ExpansionGarrisonDebt`.
///
/// Provides typed access to indexed columns for query building.
pub struct ExpansionGarrisonDebtIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<ExpansionGarrisonDebt, u32>,
}

impl __sdk::__query_builder::HasIxCols for ExpansionGarrisonDebt {
    type IxCols = ExpansionGarrisonDebtIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ExpansionGarrisonDebtIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ExpansionGarrisonDebt {}
