// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssueFrontLoadArgs {
    pub client_command_id: u64,
    pub selected_cells: Vec<u32>,
    pub orientation_q: i32,
    pub orientation_r: i32,
    pub amount_bps: u32,
}

impl From<IssueFrontLoadArgs> for super::Reducer {
    fn from(args: IssueFrontLoadArgs) -> Self {
        Self::IssueFrontLoad {
            client_command_id: args.client_command_id,
            selected_cells: args.selected_cells,
            orientation_q: args.orientation_q,
            orientation_r: args.orientation_r,
            amount_bps: args.amount_bps,
        }
    }
}

impl __sdk::InModule for IssueFrontLoadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_front_load`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_front_load {
    /// Request that the remote module invoke the reducer `issue_front_load` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_front_load:issue_front_load_then`] to run a callback after the reducer completes.
    fn issue_front_load(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        orientation_q: i32,
        orientation_r: i32,
        amount_bps: u32,
    ) -> __sdk::Result<()> {
        self.issue_front_load_then(
            client_command_id,
            selected_cells,
            orientation_q,
            orientation_r,
            amount_bps,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `issue_front_load` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_front_load_then(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        orientation_q: i32,
        orientation_r: i32,
        amount_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_front_load for super::RemoteReducers {
    fn issue_front_load_then(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        orientation_q: i32,
        orientation_r: i32,
        amount_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IssueFrontLoadArgs {
                client_command_id,
                selected_cells,
                orientation_q,
                orientation_r,
                amount_bps,
            },
            callback,
        )
    }
}
