// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssueTransferArgs {
    pub client_command_id: u64,
    pub source_cells: Vec<u32>,
    pub destination_cells: Vec<u32>,
    pub infantry: u64,
}

impl From<IssueTransferArgs> for super::Reducer {
    fn from(args: IssueTransferArgs) -> Self {
        Self::IssueTransfer {
            client_command_id: args.client_command_id,
            source_cells: args.source_cells,
            destination_cells: args.destination_cells,
            infantry: args.infantry,
        }
    }
}

impl __sdk::InModule for IssueTransferArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_transfer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_transfer {
    /// Request that the remote module invoke the reducer `issue_transfer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_transfer:issue_transfer_then`] to run a callback after the reducer completes.
    fn issue_transfer(
        &self,
        client_command_id: u64,
        source_cells: Vec<u32>,
        destination_cells: Vec<u32>,
        infantry: u64,
    ) -> __sdk::Result<()> {
        self.issue_transfer_then(
            client_command_id,
            source_cells,
            destination_cells,
            infantry,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `issue_transfer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_transfer_then(
        &self,
        client_command_id: u64,
        source_cells: Vec<u32>,
        destination_cells: Vec<u32>,
        infantry: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_transfer for super::RemoteReducers {
    fn issue_transfer_then(
        &self,
        client_command_id: u64,
        source_cells: Vec<u32>,
        destination_cells: Vec<u32>,
        infantry: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IssueTransferArgs {
                client_command_id,
                source_cells,
                destination_cells,
                infantry,
            },
            callback,
        )
    }
}
