// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssuePerimeterLoadArgs {
    pub client_command_id: u64,
    pub selected_cells: Vec<u32>,
    pub amount_bps: u32,
}

impl From<IssuePerimeterLoadArgs> for super::Reducer {
    fn from(args: IssuePerimeterLoadArgs) -> Self {
        Self::IssuePerimeterLoad {
            client_command_id: args.client_command_id,
            selected_cells: args.selected_cells,
            amount_bps: args.amount_bps,
        }
    }
}

impl __sdk::InModule for IssuePerimeterLoadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_perimeter_load`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_perimeter_load {
    /// Request that the remote module invoke the reducer `issue_perimeter_load` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_perimeter_load:issue_perimeter_load_then`] to run a callback after the reducer completes.
    fn issue_perimeter_load(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,
    ) -> __sdk::Result<()> {
        self.issue_perimeter_load_then(client_command_id, selected_cells, amount_bps, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `issue_perimeter_load` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_perimeter_load_then(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_perimeter_load for super::RemoteReducers {
    fn issue_perimeter_load_then(
        &self,
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IssuePerimeterLoadArgs {
                client_command_id,
                selected_cells,
                amount_bps,
            },
            callback,
        )
    }
}
