// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinMatchArgs {
    pub preferred_player_id: u8,
    pub display_name: String,
}

impl From<JoinMatchArgs> for super::Reducer {
    fn from(args: JoinMatchArgs) -> Self {
        Self::JoinMatch {
            preferred_player_id: args.preferred_player_id,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for JoinMatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join_match`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join_match {
    /// Request that the remote module invoke the reducer `join_match` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`join_match:join_match_then`] to run a callback after the reducer completes.
    fn join_match(&self, preferred_player_id: u8, display_name: String) -> __sdk::Result<()> {
        self.join_match_then(preferred_player_id, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `join_match` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn join_match_then(
        &self,
        preferred_player_id: u8,
        display_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl join_match for super::RemoteReducers {
    fn join_match_then(
        &self,
        preferred_player_id: u8,
        display_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            JoinMatchArgs {
                preferred_player_id,
                display_name,
            },
            callback,
        )
    }
}
