// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyConfigurator {
    pub singleton_id: u8,
    pub identity: __sdk::Identity,
}

impl __sdk::InModule for LobbyConfigurator {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LobbyConfigurator`.
///
/// Provides typed access to columns for query building.
pub struct LobbyConfiguratorCols {
    pub singleton_id: __sdk::__query_builder::Col<LobbyConfigurator, u8>,
    pub identity: __sdk::__query_builder::Col<LobbyConfigurator, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for LobbyConfigurator {
    type Cols = LobbyConfiguratorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyConfiguratorCols {
            singleton_id: __sdk::__query_builder::Col::new(table_name, "singleton_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
        }
    }
}

/// Indexed column accessor struct for the table `LobbyConfigurator`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyConfiguratorIxCols {
    pub singleton_id: __sdk::__query_builder::IxCol<LobbyConfigurator, u8>,
}

impl __sdk::__query_builder::HasIxCols for LobbyConfigurator {
    type IxCols = LobbyConfiguratorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyConfiguratorIxCols {
            singleton_id: __sdk::__query_builder::IxCol::new(table_name, "singleton_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LobbyConfigurator {}
