// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_preset_type::MapPreset;
use super::match_config_type::MatchConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_config`.
///
/// Obtain a handle from the [`MatchConfigTableAccess::match_config`] method on [`super::RemoteTables`],
/// like `ctx.db.match_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_config().on_insert(...)`.
pub struct MatchConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_config`.
pub struct MatchConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchConfigTableAccessor {
    type Row = MatchConfig;
    type Handle<'db> = MatchConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchConfigTableHandle`], which mediates access to the table `match_config`.
    fn match_config(&self) -> MatchConfigTableHandle<'_>;
}

impl MatchConfigTableAccess for super::RemoteTables {
    fn match_config(&self) -> MatchConfigTableHandle<'_> {
        MatchConfigTableHandle {
            imp: self.imp.get_table::<MatchConfig>("match_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchConfigInsertCallbackId(__sdk::CallbackId);
pub struct MatchConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchConfigTableHandle<'ctx> {
    type Row = MatchConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchConfigTableHandle<'ctx> {
    type Row = MatchConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchConfigInsertCallbackId {
        MatchConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchConfigDeleteCallbackId {
        MatchConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchConfigTableHandle<'ctx> {
    type InsertCallbackId = MatchConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchConfigInsertCallbackId {
        MatchConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchConfigTableHandle<'ctx> {
    type DeleteCallbackId = MatchConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchConfigDeleteCallbackId {
        MatchConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchConfigTableHandle<'ctx> {
    type UpdateCallbackId = MatchConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchConfigUpdateCallbackId {
        MatchConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchConfigTableHandle<'ctx> {
    type UpdateCallbackId = MatchConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchConfigUpdateCallbackId {
        MatchConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `singleton_id` unique index on the table `match_config`,
/// which allows point queries on the field of the same name
/// via the [`MatchConfigSingletonIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_config().singleton_id().find(...)`.
pub struct MatchConfigSingletonIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchConfig, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchConfigTableHandle<'ctx> {
    /// Get a handle on the `singleton_id` unique index on the table `match_config`.
    pub fn singleton_id(&self) -> MatchConfigSingletonIdUnique<'ctx> {
        MatchConfigSingletonIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("singleton_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchConfigSingletonIdUnique<'ctx> {
    /// Find the subscribed row whose `singleton_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<MatchConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchConfig>("match_config");
    _table.add_unique_constraint::<u8>("singleton_id", |row| &row.singleton_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchConfig`.
    fn match_config(&self) -> __sdk::__query_builder::Table<MatchConfig>;
}

impl match_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_config(&self) -> __sdk::__query_builder::Table<MatchConfig> {
        __sdk::__query_builder::Table::new("match_config")
    }
}
