// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::match_phase_type::MatchPhase;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchState {
    pub singleton_id: u8,
    pub phase: MatchPhase,
    pub logical_step: u64,
    pub capturable_cells: u64,
    pub required_control: u64,
    pub player_one_controlled: u64,
    pub player_two_controlled: u64,
    pub winner_player_id: u8,
    pub latest_cluster_policy_revision: u64,
    pub started_at_us: u64,
    pub completed_at_us: u64,
}

impl __sdk::InModule for MatchState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchState`.
///
/// Provides typed access to columns for query building.
pub struct MatchStateCols {
    pub singleton_id: __sdk::__query_builder::Col<MatchState, u8>,
    pub phase: __sdk::__query_builder::Col<MatchState, MatchPhase>,
    pub logical_step: __sdk::__query_builder::Col<MatchState, u64>,
    pub capturable_cells: __sdk::__query_builder::Col<MatchState, u64>,
    pub required_control: __sdk::__query_builder::Col<MatchState, u64>,
    pub player_one_controlled: __sdk::__query_builder::Col<MatchState, u64>,
    pub player_two_controlled: __sdk::__query_builder::Col<MatchState, u64>,
    pub winner_player_id: __sdk::__query_builder::Col<MatchState, u8>,
    pub latest_cluster_policy_revision: __sdk::__query_builder::Col<MatchState, u64>,
    pub started_at_us: __sdk::__query_builder::Col<MatchState, u64>,
    pub completed_at_us: __sdk::__query_builder::Col<MatchState, u64>,
}

impl __sdk::__query_builder::HasCols for MatchState {
    type Cols = MatchStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchStateCols {
            singleton_id: __sdk::__query_builder::Col::new(table_name, "singleton_id"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            logical_step: __sdk::__query_builder::Col::new(table_name, "logical_step"),
            capturable_cells: __sdk::__query_builder::Col::new(table_name, "capturable_cells"),
            required_control: __sdk::__query_builder::Col::new(table_name, "required_control"),
            player_one_controlled: __sdk::__query_builder::Col::new(
                table_name,
                "player_one_controlled",
            ),
            player_two_controlled: __sdk::__query_builder::Col::new(
                table_name,
                "player_two_controlled",
            ),
            winner_player_id: __sdk::__query_builder::Col::new(table_name, "winner_player_id"),
            latest_cluster_policy_revision: __sdk::__query_builder::Col::new(
                table_name,
                "latest_cluster_policy_revision",
            ),
            started_at_us: __sdk::__query_builder::Col::new(table_name, "started_at_us"),
            completed_at_us: __sdk::__query_builder::Col::new(table_name, "completed_at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchState`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchStateIxCols {
    pub singleton_id: __sdk::__query_builder::IxCol<MatchState, u8>,
}

impl __sdk::__query_builder::HasIxCols for MatchState {
    type IxCols = MatchStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchStateIxCols {
            singleton_id: __sdk::__query_builder::IxCol::new(table_name, "singleton_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchState {}
