// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::map_preset_type::MapPreset;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchConfig {
    pub singleton_id: u8,
    pub map_preset: MapPreset,
    pub map_seed: u64,
    pub map_width: u16,
    pub map_height: u16,
    pub map_q_min: i32,
    pub map_r_min: i32,
    pub chunk_size: u16,
    pub logical_step_ms: u32,
    pub population_step_interval: u32,
    pub base_military_capacity: u64,
    pub base_edge_throughput_per_second: u64,
    pub base_combat_frontage: u64,
    pub max_elevation_step: u8,
    pub uphill_attack_bps: u32,
    pub combat_lethality_bps: u32,
    pub civilian_growth_bps: u32,
    pub mobilization_per_population_step: u64,
    pub conquest_threshold_bps: u32,
    pub map_hash: u64,
    pub spawn_one_cell: u32,
    pub spawn_two_cell: u32,
}

impl __sdk::InModule for MatchConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchConfig`.
///
/// Provides typed access to columns for query building.
pub struct MatchConfigCols {
    pub singleton_id: __sdk::__query_builder::Col<MatchConfig, u8>,
    pub map_preset: __sdk::__query_builder::Col<MatchConfig, MapPreset>,
    pub map_seed: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub map_width: __sdk::__query_builder::Col<MatchConfig, u16>,
    pub map_height: __sdk::__query_builder::Col<MatchConfig, u16>,
    pub map_q_min: __sdk::__query_builder::Col<MatchConfig, i32>,
    pub map_r_min: __sdk::__query_builder::Col<MatchConfig, i32>,
    pub chunk_size: __sdk::__query_builder::Col<MatchConfig, u16>,
    pub logical_step_ms: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub population_step_interval: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub base_military_capacity: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub base_edge_throughput_per_second: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub base_combat_frontage: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub max_elevation_step: __sdk::__query_builder::Col<MatchConfig, u8>,
    pub uphill_attack_bps: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub combat_lethality_bps: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub civilian_growth_bps: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub mobilization_per_population_step: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub conquest_threshold_bps: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub map_hash: __sdk::__query_builder::Col<MatchConfig, u64>,
    pub spawn_one_cell: __sdk::__query_builder::Col<MatchConfig, u32>,
    pub spawn_two_cell: __sdk::__query_builder::Col<MatchConfig, u32>,
}

impl __sdk::__query_builder::HasCols for MatchConfig {
    type Cols = MatchConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchConfigCols {
            singleton_id: __sdk::__query_builder::Col::new(table_name, "singleton_id"),
            map_preset: __sdk::__query_builder::Col::new(table_name, "map_preset"),
            map_seed: __sdk::__query_builder::Col::new(table_name, "map_seed"),
            map_width: __sdk::__query_builder::Col::new(table_name, "map_width"),
            map_height: __sdk::__query_builder::Col::new(table_name, "map_height"),
            map_q_min: __sdk::__query_builder::Col::new(table_name, "map_q_min"),
            map_r_min: __sdk::__query_builder::Col::new(table_name, "map_r_min"),
            chunk_size: __sdk::__query_builder::Col::new(table_name, "chunk_size"),
            logical_step_ms: __sdk::__query_builder::Col::new(table_name, "logical_step_ms"),
            population_step_interval: __sdk::__query_builder::Col::new(
                table_name,
                "population_step_interval",
            ),
            base_military_capacity: __sdk::__query_builder::Col::new(
                table_name,
                "base_military_capacity",
            ),
            base_edge_throughput_per_second: __sdk::__query_builder::Col::new(
                table_name,
                "base_edge_throughput_per_second",
            ),
            base_combat_frontage: __sdk::__query_builder::Col::new(
                table_name,
                "base_combat_frontage",
            ),
            max_elevation_step: __sdk::__query_builder::Col::new(table_name, "max_elevation_step"),
            uphill_attack_bps: __sdk::__query_builder::Col::new(table_name, "uphill_attack_bps"),
            combat_lethality_bps: __sdk::__query_builder::Col::new(
                table_name,
                "combat_lethality_bps",
            ),
            civilian_growth_bps: __sdk::__query_builder::Col::new(
                table_name,
                "civilian_growth_bps",
            ),
            mobilization_per_population_step: __sdk::__query_builder::Col::new(
                table_name,
                "mobilization_per_population_step",
            ),
            conquest_threshold_bps: __sdk::__query_builder::Col::new(
                table_name,
                "conquest_threshold_bps",
            ),
            map_hash: __sdk::__query_builder::Col::new(table_name, "map_hash"),
            spawn_one_cell: __sdk::__query_builder::Col::new(table_name, "spawn_one_cell"),
            spawn_two_cell: __sdk::__query_builder::Col::new(table_name, "spawn_two_cell"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchConfigIxCols {
    pub singleton_id: __sdk::__query_builder::IxCol<MatchConfig, u8>,
}

impl __sdk::__query_builder::HasIxCols for MatchConfig {
    type IxCols = MatchConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchConfigIxCols {
            singleton_id: __sdk::__query_builder::IxCol::new(table_name, "singleton_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchConfig {}
