// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mobilization_policy_type::MobilizationPolicy;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mobilization_policy`.
///
/// Obtain a handle from the [`MobilizationPolicyTableAccess::mobilization_policy`] method on [`super::RemoteTables`],
/// like `ctx.db.mobilization_policy()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mobilization_policy().on_insert(...)`.
pub struct MobilizationPolicyTableHandle<'ctx> {
    imp: __sdk::TableHandle<MobilizationPolicy>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `mobilization_policy`.
pub struct MobilizationPolicyTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MobilizationPolicyTableAccessor {
    type Row = MobilizationPolicy;
    type Handle<'db> = MobilizationPolicyTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.mobilization_policy()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mobilization_policy`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MobilizationPolicyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MobilizationPolicyTableHandle`], which mediates access to the table `mobilization_policy`.
    fn mobilization_policy(&self) -> MobilizationPolicyTableHandle<'_>;
}

impl MobilizationPolicyTableAccess for super::RemoteTables {
    fn mobilization_policy(&self) -> MobilizationPolicyTableHandle<'_> {
        MobilizationPolicyTableHandle {
            imp: self
                .imp
                .get_table::<MobilizationPolicy>("mobilization_policy"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MobilizationPolicyInsertCallbackId(__sdk::CallbackId);
pub struct MobilizationPolicyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MobilizationPolicyTableHandle<'ctx> {
    type Row = MobilizationPolicy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MobilizationPolicy> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MobilizationPolicyTableHandle<'ctx> {
    type Row = MobilizationPolicy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MobilizationPolicy> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MobilizationPolicyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyInsertCallbackId {
        MobilizationPolicyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MobilizationPolicyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MobilizationPolicyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyDeleteCallbackId {
        MobilizationPolicyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MobilizationPolicyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MobilizationPolicyTableHandle<'ctx> {
    type InsertCallbackId = MobilizationPolicyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyInsertCallbackId {
        MobilizationPolicyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MobilizationPolicyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MobilizationPolicyTableHandle<'ctx> {
    type DeleteCallbackId = MobilizationPolicyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyDeleteCallbackId {
        MobilizationPolicyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MobilizationPolicyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MobilizationPolicyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MobilizationPolicyTableHandle<'ctx> {
    type UpdateCallbackId = MobilizationPolicyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyUpdateCallbackId {
        MobilizationPolicyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MobilizationPolicyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MobilizationPolicyTableHandle<'ctx> {
    type UpdateCallbackId = MobilizationPolicyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MobilizationPolicyUpdateCallbackId {
        MobilizationPolicyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MobilizationPolicyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player_id` unique index on the table `mobilization_policy`,
/// which allows point queries on the field of the same name
/// via the [`MobilizationPolicyPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mobilization_policy().player_id().find(...)`.
pub struct MobilizationPolicyPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MobilizationPolicy, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MobilizationPolicyTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `mobilization_policy`.
    pub fn player_id(&self) -> MobilizationPolicyPlayerIdUnique<'ctx> {
        MobilizationPolicyPlayerIdUnique {
            imp: self.imp.get_unique_constraint::<u16>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MobilizationPolicyPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<MobilizationPolicy> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MobilizationPolicy>("mobilization_policy");
    _table.add_unique_constraint::<u16>("player_id", |row| &row.player_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MobilizationPolicy>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MobilizationPolicy>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MobilizationPolicy`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait mobilization_policyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MobilizationPolicy`.
    fn mobilization_policy(&self) -> __sdk::__query_builder::Table<MobilizationPolicy>;
}

impl mobilization_policyQueryTableAccess for __sdk::QueryTableAccessor {
    fn mobilization_policy(&self) -> __sdk::__query_builder::Table<MobilizationPolicy> {
        __sdk::__query_builder::Table::new("mobilization_policy")
    }
}
