// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MobilizationPolicy {
    pub player_id: u8,
    pub target_bps: u32,
}

impl __sdk::InModule for MobilizationPolicy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MobilizationPolicy`.
///
/// Provides typed access to columns for query building.
pub struct MobilizationPolicyCols {
    pub player_id: __sdk::__query_builder::Col<MobilizationPolicy, u8>,
    pub target_bps: __sdk::__query_builder::Col<MobilizationPolicy, u32>,
}

impl __sdk::__query_builder::HasCols for MobilizationPolicy {
    type Cols = MobilizationPolicyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MobilizationPolicyCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            target_bps: __sdk::__query_builder::Col::new(table_name, "target_bps"),
        }
    }
}

/// Indexed column accessor struct for the table `MobilizationPolicy`.
///
/// Provides typed access to indexed columns for query building.
pub struct MobilizationPolicyIxCols {
    pub player_id: __sdk::__query_builder::IxCol<MobilizationPolicy, u8>,
}

impl __sdk::__query_builder::HasIxCols for MobilizationPolicy {
    type IxCols = MobilizationPolicyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MobilizationPolicyIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MobilizationPolicy {}
