// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.1 (commit 8ecd3c3bac427a49a9d9b13671bf83324afa59ba).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod cancel_push_fronts_reducer;
pub mod cell_state_table;
pub mod cell_state_type;
pub mod cell_terrain_table;
pub mod cell_terrain_type;
pub mod combat_front_table;
pub mod combat_front_type;
pub mod command_receipt_table;
pub mod command_receipt_type;
pub mod configure_map_reducer;
pub mod issue_balance_reducer;
pub mod issue_core_load_reducer;
pub mod issue_front_load_reducer;
pub mod issue_perimeter_load_reducer;
pub mod issue_push_front_reducer;
pub mod join_match_reducer;
pub mod map_preset_type;
pub mod match_config_table;
pub mod match_config_type;
pub mod match_phase_type;
pub mod match_state_table;
pub mod match_state_type;
pub mod mobilization_policy_table;
pub mod mobilization_policy_type;
pub mod order_kind_type;
pub mod order_status_type;
pub mod player_slot_table;
pub mod player_slot_type;
pub mod receipt_status_type;
pub mod set_mobilization_target_reducer;
pub mod simulation_schedule_type;
pub mod terrain_class_type;
pub mod transfer_destination_table;
pub mod transfer_destination_type;
pub mod transfer_order_table;
pub mod transfer_order_type;
pub mod transfer_source_table;
pub mod transfer_source_type;
pub mod transit_packet_table;
pub mod transit_packet_type;

pub use cancel_push_fronts_reducer::cancel_push_fronts;
pub use cell_state_table::*;
pub use cell_state_type::CellState;
pub use cell_terrain_table::*;
pub use cell_terrain_type::CellTerrain;
pub use combat_front_table::*;
pub use combat_front_type::CombatFront;
pub use command_receipt_table::*;
pub use command_receipt_type::CommandReceipt;
pub use configure_map_reducer::configure_map;
pub use issue_balance_reducer::issue_balance;
pub use issue_core_load_reducer::issue_core_load;
pub use issue_front_load_reducer::issue_front_load;
pub use issue_perimeter_load_reducer::issue_perimeter_load;
pub use issue_push_front_reducer::issue_push_front;
pub use join_match_reducer::join_match;
pub use map_preset_type::MapPreset;
pub use match_config_table::*;
pub use match_config_type::MatchConfig;
pub use match_phase_type::MatchPhase;
pub use match_state_table::*;
pub use match_state_type::MatchState;
pub use mobilization_policy_table::*;
pub use mobilization_policy_type::MobilizationPolicy;
pub use order_kind_type::OrderKind;
pub use order_status_type::OrderStatus;
pub use player_slot_table::*;
pub use player_slot_type::PlayerSlot;
pub use receipt_status_type::ReceiptStatus;
pub use set_mobilization_target_reducer::set_mobilization_target;
pub use simulation_schedule_type::SimulationSchedule;
pub use terrain_class_type::TerrainClass;
pub use transfer_destination_table::*;
pub use transfer_destination_type::TransferDestination;
pub use transfer_order_table::*;
pub use transfer_order_type::TransferOrder;
pub use transfer_source_table::*;
pub use transfer_source_type::TransferSource;
pub use transit_packet_table::*;
pub use transit_packet_type::TransitPacket;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CancelPushFronts {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        direction_q: i32,
        direction_r: i32,
    },
    ConfigureMap {
        preset: MapPreset,
    },
    IssueBalance {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,
    },
    IssueCoreLoad {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,
    },
    IssueFrontLoad {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        orientation_q: i32,
        orientation_r: i32,
        amount_bps: u32,
    },
    IssuePerimeterLoad {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        amount_bps: u32,
    },
    IssuePushFront {
        client_command_id: u64,
        selected_cells: Vec<u32>,
        direction_q: i32,
        direction_r: i32,
        commitment_bps: u32,
    },
    JoinMatch {
        preferred_player_id: u8,
        display_name: String,
    },
    SetMobilizationTarget {
        client_command_id: u64,
        target_bps: u32,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CancelPushFronts { .. } => "cancel_push_fronts",
            Reducer::ConfigureMap { .. } => "configure_map",
            Reducer::IssueBalance { .. } => "issue_balance",
            Reducer::IssueCoreLoad { .. } => "issue_core_load",
            Reducer::IssueFrontLoad { .. } => "issue_front_load",
            Reducer::IssuePerimeterLoad { .. } => "issue_perimeter_load",
            Reducer::IssuePushFront { .. } => "issue_push_front",
            Reducer::JoinMatch { .. } => "join_match",
            Reducer::SetMobilizationTarget { .. } => "set_mobilization_target",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::CancelPushFronts {
                client_command_id,
                selected_cells,
                direction_q,
                direction_r,
            } => __sats::bsatn::to_vec(&cancel_push_fronts_reducer::CancelPushFrontsArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                direction_q: direction_q.clone(),
                direction_r: direction_r.clone(),
            }),
            Reducer::ConfigureMap { preset } => {
                __sats::bsatn::to_vec(&configure_map_reducer::ConfigureMapArgs {
                    preset: preset.clone(),
                })
            }
            Reducer::IssueBalance {
                client_command_id,
                selected_cells,
                amount_bps,
            } => __sats::bsatn::to_vec(&issue_balance_reducer::IssueBalanceArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                amount_bps: amount_bps.clone(),
            }),
            Reducer::IssueCoreLoad {
                client_command_id,
                selected_cells,
                amount_bps,
            } => __sats::bsatn::to_vec(&issue_core_load_reducer::IssueCoreLoadArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                amount_bps: amount_bps.clone(),
            }),
            Reducer::IssueFrontLoad {
                client_command_id,
                selected_cells,
                orientation_q,
                orientation_r,
                amount_bps,
            } => __sats::bsatn::to_vec(&issue_front_load_reducer::IssueFrontLoadArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                orientation_q: orientation_q.clone(),
                orientation_r: orientation_r.clone(),
                amount_bps: amount_bps.clone(),
            }),
            Reducer::IssuePerimeterLoad {
                client_command_id,
                selected_cells,
                amount_bps,
            } => __sats::bsatn::to_vec(&issue_perimeter_load_reducer::IssuePerimeterLoadArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                amount_bps: amount_bps.clone(),
            }),
            Reducer::IssuePushFront {
                client_command_id,
                selected_cells,
                direction_q,
                direction_r,
                commitment_bps,
            } => __sats::bsatn::to_vec(&issue_push_front_reducer::IssuePushFrontArgs {
                client_command_id: client_command_id.clone(),
                selected_cells: selected_cells.clone(),
                direction_q: direction_q.clone(),
                direction_r: direction_r.clone(),
                commitment_bps: commitment_bps.clone(),
            }),
            Reducer::JoinMatch {
                preferred_player_id,
                display_name,
            } => __sats::bsatn::to_vec(&join_match_reducer::JoinMatchArgs {
                preferred_player_id: preferred_player_id.clone(),
                display_name: display_name.clone(),
            }),
            Reducer::SetMobilizationTarget {
                client_command_id,
                target_bps,
            } => __sats::bsatn::to_vec(
                &set_mobilization_target_reducer::SetMobilizationTargetArgs {
                    client_command_id: client_command_id.clone(),
                    target_bps: target_bps.clone(),
                },
            ),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    cell_state: __sdk::TableUpdate<CellState>,
    cell_terrain: __sdk::TableUpdate<CellTerrain>,
    combat_front: __sdk::TableUpdate<CombatFront>,
    command_receipt: __sdk::TableUpdate<CommandReceipt>,
    match_config: __sdk::TableUpdate<MatchConfig>,
    match_state: __sdk::TableUpdate<MatchState>,
    mobilization_policy: __sdk::TableUpdate<MobilizationPolicy>,
    player_slot: __sdk::TableUpdate<PlayerSlot>,
    transfer_destination: __sdk::TableUpdate<TransferDestination>,
    transfer_order: __sdk::TableUpdate<TransferOrder>,
    transfer_source: __sdk::TableUpdate<TransferSource>,
    transit_packet: __sdk::TableUpdate<TransitPacket>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "cell_state" => db_update
                    .cell_state
                    .append(cell_state_table::parse_table_update(table_update)?),
                "cell_terrain" => db_update
                    .cell_terrain
                    .append(cell_terrain_table::parse_table_update(table_update)?),
                "combat_front" => db_update
                    .combat_front
                    .append(combat_front_table::parse_table_update(table_update)?),
                "command_receipt" => db_update
                    .command_receipt
                    .append(command_receipt_table::parse_table_update(table_update)?),
                "match_config" => db_update
                    .match_config
                    .append(match_config_table::parse_table_update(table_update)?),
                "match_state" => db_update
                    .match_state
                    .append(match_state_table::parse_table_update(table_update)?),
                "mobilization_policy" => db_update
                    .mobilization_policy
                    .append(mobilization_policy_table::parse_table_update(table_update)?),
                "player_slot" => db_update
                    .player_slot
                    .append(player_slot_table::parse_table_update(table_update)?),
                "transfer_destination" => db_update.transfer_destination.append(
                    transfer_destination_table::parse_table_update(table_update)?,
                ),
                "transfer_order" => db_update
                    .transfer_order
                    .append(transfer_order_table::parse_table_update(table_update)?),
                "transfer_source" => db_update
                    .transfer_source
                    .append(transfer_source_table::parse_table_update(table_update)?),
                "transit_packet" => db_update
                    .transit_packet
                    .append(transit_packet_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.cell_state = cache
            .apply_diff_to_table::<CellState>("cell_state", &self.cell_state)
            .with_updates_by_pk(|row| &row.cell_id);
        diff.cell_terrain = cache
            .apply_diff_to_table::<CellTerrain>("cell_terrain", &self.cell_terrain)
            .with_updates_by_pk(|row| &row.cell_id);
        diff.combat_front = cache
            .apply_diff_to_table::<CombatFront>("combat_front", &self.combat_front)
            .with_updates_by_pk(|row| &row.front_key);
        diff.command_receipt = cache
            .apply_diff_to_table::<CommandReceipt>("command_receipt", &self.command_receipt)
            .with_updates_by_pk(|row| &row.receipt_key);
        diff.match_config = cache
            .apply_diff_to_table::<MatchConfig>("match_config", &self.match_config)
            .with_updates_by_pk(|row| &row.singleton_id);
        diff.match_state = cache
            .apply_diff_to_table::<MatchState>("match_state", &self.match_state)
            .with_updates_by_pk(|row| &row.singleton_id);
        diff.mobilization_policy = cache
            .apply_diff_to_table::<MobilizationPolicy>(
                "mobilization_policy",
                &self.mobilization_policy,
            )
            .with_updates_by_pk(|row| &row.player_id);
        diff.player_slot = cache
            .apply_diff_to_table::<PlayerSlot>("player_slot", &self.player_slot)
            .with_updates_by_pk(|row| &row.player_id);
        diff.transfer_destination = cache
            .apply_diff_to_table::<TransferDestination>(
                "transfer_destination",
                &self.transfer_destination,
            )
            .with_updates_by_pk(|row| &row.destination_key);
        diff.transfer_order = cache
            .apply_diff_to_table::<TransferOrder>("transfer_order", &self.transfer_order)
            .with_updates_by_pk(|row| &row.order_id);
        diff.transfer_source = cache
            .apply_diff_to_table::<TransferSource>("transfer_source", &self.transfer_source)
            .with_updates_by_pk(|row| &row.source_key);
        diff.transit_packet = cache
            .apply_diff_to_table::<TransitPacket>("transit_packet", &self.transit_packet)
            .with_updates_by_pk(|row| &row.packet_key);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "cell_state" => db_update
                    .cell_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cell_terrain" => db_update
                    .cell_terrain
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "combat_front" => db_update
                    .combat_front
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "command_receipt" => db_update
                    .command_receipt
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_config" => db_update
                    .match_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_state" => db_update
                    .match_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "mobilization_policy" => db_update
                    .mobilization_policy
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_slot" => db_update
                    .player_slot
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transfer_destination" => db_update
                    .transfer_destination
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transfer_order" => db_update
                    .transfer_order
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transfer_source" => db_update
                    .transfer_source
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "transit_packet" => db_update
                    .transit_packet
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "cell_state" => db_update
                    .cell_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cell_terrain" => db_update
                    .cell_terrain
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "combat_front" => db_update
                    .combat_front
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "command_receipt" => db_update
                    .command_receipt
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_config" => db_update
                    .match_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_state" => db_update
                    .match_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "mobilization_policy" => db_update
                    .mobilization_policy
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_slot" => db_update
                    .player_slot
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transfer_destination" => db_update
                    .transfer_destination
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transfer_order" => db_update
                    .transfer_order
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transfer_source" => db_update
                    .transfer_source
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "transit_packet" => db_update
                    .transit_packet
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    cell_state: __sdk::TableAppliedDiff<'r, CellState>,
    cell_terrain: __sdk::TableAppliedDiff<'r, CellTerrain>,
    combat_front: __sdk::TableAppliedDiff<'r, CombatFront>,
    command_receipt: __sdk::TableAppliedDiff<'r, CommandReceipt>,
    match_config: __sdk::TableAppliedDiff<'r, MatchConfig>,
    match_state: __sdk::TableAppliedDiff<'r, MatchState>,
    mobilization_policy: __sdk::TableAppliedDiff<'r, MobilizationPolicy>,
    player_slot: __sdk::TableAppliedDiff<'r, PlayerSlot>,
    transfer_destination: __sdk::TableAppliedDiff<'r, TransferDestination>,
    transfer_order: __sdk::TableAppliedDiff<'r, TransferOrder>,
    transfer_source: __sdk::TableAppliedDiff<'r, TransferSource>,
    transit_packet: __sdk::TableAppliedDiff<'r, TransitPacket>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<CellState>("cell_state", &self.cell_state, event);
        callbacks.invoke_table_row_callbacks::<CellTerrain>(
            "cell_terrain",
            &self.cell_terrain,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CombatFront>(
            "combat_front",
            &self.combat_front,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CommandReceipt>(
            "command_receipt",
            &self.command_receipt,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchConfig>(
            "match_config",
            &self.match_config,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchState>("match_state", &self.match_state, event);
        callbacks.invoke_table_row_callbacks::<MobilizationPolicy>(
            "mobilization_policy",
            &self.mobilization_policy,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSlot>("player_slot", &self.player_slot, event);
        callbacks.invoke_table_row_callbacks::<TransferDestination>(
            "transfer_destination",
            &self.transfer_destination,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TransferOrder>(
            "transfer_order",
            &self.transfer_order,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TransferSource>(
            "transfer_source",
            &self.transfer_source,
            event,
        );
        callbacks.invoke_table_row_callbacks::<TransitPacket>(
            "transit_packet",
            &self.transit_packet,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
        DbView = RemoteTables,
        Reducers = RemoteReducers,
        SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
    >
{
}
impl<
    Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
> RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        cell_state_table::register_table(client_cache);
        cell_terrain_table::register_table(client_cache);
        combat_front_table::register_table(client_cache);
        command_receipt_table::register_table(client_cache);
        match_config_table::register_table(client_cache);
        match_state_table::register_table(client_cache);
        mobilization_policy_table::register_table(client_cache);
        player_slot_table::register_table(client_cache);
        transfer_destination_table::register_table(client_cache);
        transfer_order_table::register_table(client_cache);
        transfer_source_table::register_table(client_cache);
        transit_packet_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "cell_state",
        "cell_terrain",
        "combat_front",
        "command_receipt",
        "match_config",
        "match_state",
        "mobilization_policy",
        "player_slot",
        "transfer_destination",
        "transfer_order",
        "transfer_source",
        "transit_packet",
    ];
}
