// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerState {
    pub player_id: u16,
    pub spawn_cell_id: u32,
    pub controlled_cells: u64,
}

impl __sdk::InModule for PlayerState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerState`.
///
/// Provides typed access to columns for query building.
pub struct PlayerStateCols {
    pub player_id: __sdk::__query_builder::Col<PlayerState, u16>,
    pub spawn_cell_id: __sdk::__query_builder::Col<PlayerState, u32>,
    pub controlled_cells: __sdk::__query_builder::Col<PlayerState, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerState {
    type Cols = PlayerStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerStateCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            spawn_cell_id: __sdk::__query_builder::Col::new(table_name, "spawn_cell_id"),
            controlled_cells: __sdk::__query_builder::Col::new(table_name, "controlled_cells"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerState`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerStateIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerState, u16>,
}

impl __sdk::__query_builder::HasIxCols for PlayerState {
    type IxCols = PlayerStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerStateIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerState {}
