// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSlot {
    pub player_id: u16,
    pub identity: Option<__sdk::Identity>,
    pub display_name: String,
    pub connected: bool,
    pub has_reconnected: bool,
    pub reconnect_count: u32,
    pub ready: bool,
    pub joined_at_us: u64,
    pub last_seen_at_us: u64,
}

impl __sdk::InModule for PlayerSlot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSlot`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSlotCols {
    pub player_id: __sdk::__query_builder::Col<PlayerSlot, u16>,
    pub identity: __sdk::__query_builder::Col<PlayerSlot, Option<__sdk::Identity>>,
    pub display_name: __sdk::__query_builder::Col<PlayerSlot, String>,
    pub connected: __sdk::__query_builder::Col<PlayerSlot, bool>,
    pub has_reconnected: __sdk::__query_builder::Col<PlayerSlot, bool>,
    pub reconnect_count: __sdk::__query_builder::Col<PlayerSlot, u32>,
    pub ready: __sdk::__query_builder::Col<PlayerSlot, bool>,
    pub joined_at_us: __sdk::__query_builder::Col<PlayerSlot, u64>,
    pub last_seen_at_us: __sdk::__query_builder::Col<PlayerSlot, u64>,
}

impl __sdk::__query_builder::HasCols for PlayerSlot {
    type Cols = PlayerSlotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSlotCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            connected: __sdk::__query_builder::Col::new(table_name, "connected"),
            has_reconnected: __sdk::__query_builder::Col::new(table_name, "has_reconnected"),
            reconnect_count: __sdk::__query_builder::Col::new(table_name, "reconnect_count"),
            ready: __sdk::__query_builder::Col::new(table_name, "ready"),
            joined_at_us: __sdk::__query_builder::Col::new(table_name, "joined_at_us"),
            last_seen_at_us: __sdk::__query_builder::Col::new(table_name, "last_seen_at_us"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSlot`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSlotIxCols {
    pub player_id: __sdk::__query_builder::IxCol<PlayerSlot, u16>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSlot {
    type IxCols = PlayerSlotIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSlotIxCols {
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSlot {}
