// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_slot_type::PlayerSlot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_slot`.
///
/// Obtain a handle from the [`PlayerSlotTableAccess::player_slot`] method on [`super::RemoteTables`],
/// like `ctx.db.player_slot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_slot().on_insert(...)`.
pub struct PlayerSlotTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSlot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `player_slot`.
pub struct PlayerSlotTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlayerSlotTableAccessor {
    type Row = PlayerSlot;
    type Handle<'db> = PlayerSlotTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.player_slot()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_slot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerSlotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerSlotTableHandle`], which mediates access to the table `player_slot`.
    fn player_slot(&self) -> PlayerSlotTableHandle<'_>;
}

impl PlayerSlotTableAccess for super::RemoteTables {
    fn player_slot(&self) -> PlayerSlotTableHandle<'_> {
        PlayerSlotTableHandle {
            imp: self.imp.get_table::<PlayerSlot>("player_slot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerSlotInsertCallbackId(__sdk::CallbackId);
pub struct PlayerSlotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlayerSlotTableHandle<'ctx> {
    type Row = PlayerSlot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSlot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PlayerSlotTableHandle<'ctx> {
    type Row = PlayerSlot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSlot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerSlotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSlotInsertCallbackId {
        PlayerSlotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSlotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerSlotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSlotDeleteCallbackId {
        PlayerSlotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSlotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlayerSlotTableHandle<'ctx> {
    type InsertCallbackId = PlayerSlotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSlotInsertCallbackId {
        PlayerSlotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSlotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PlayerSlotTableHandle<'ctx> {
    type DeleteCallbackId = PlayerSlotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSlotDeleteCallbackId {
        PlayerSlotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSlotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerSlotUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerSlotTableHandle<'ctx> {
    type UpdateCallbackId = PlayerSlotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerSlotUpdateCallbackId {
        PlayerSlotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerSlotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PlayerSlotTableHandle<'ctx> {
    type UpdateCallbackId = PlayerSlotUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerSlotUpdateCallbackId {
        PlayerSlotUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerSlotUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `player_id` unique index on the table `player_slot`,
/// which allows point queries on the field of the same name
/// via the [`PlayerSlotPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_slot().player_id().find(...)`.
pub struct PlayerSlotPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerSlot, u16>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerSlotTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `player_slot`.
    pub fn player_id(&self) -> PlayerSlotPlayerIdUnique<'ctx> {
        PlayerSlotPlayerIdUnique {
            imp: self.imp.get_unique_constraint::<u16>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerSlotPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u16) -> Option<PlayerSlot> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSlot>("player_slot");
    _table.add_unique_constraint::<u16>("player_id", |row| &row.player_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSlot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSlot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerSlot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_slotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerSlot`.
    fn player_slot(&self) -> __sdk::__query_builder::Table<PlayerSlot>;
}

impl player_slotQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_slot(&self) -> __sdk::__query_builder::Table<PlayerSlot> {
        __sdk::__query_builder::Table::new("player_slot")
    }
}
