// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PolicyReplanState {
    pub component_key: u64,
    pub shape_hash: u64,
    pub policy_revision: u64,
    pub last_plan_step: u64,
}

impl __sdk::InModule for PolicyReplanState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PolicyReplanState`.
///
/// Provides typed access to columns for query building.
pub struct PolicyReplanStateCols {
    pub component_key: __sdk::__query_builder::Col<PolicyReplanState, u64>,
    pub shape_hash: __sdk::__query_builder::Col<PolicyReplanState, u64>,
    pub policy_revision: __sdk::__query_builder::Col<PolicyReplanState, u64>,
    pub last_plan_step: __sdk::__query_builder::Col<PolicyReplanState, u64>,
}

impl __sdk::__query_builder::HasCols for PolicyReplanState {
    type Cols = PolicyReplanStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PolicyReplanStateCols {
            component_key: __sdk::__query_builder::Col::new(table_name, "component_key"),
            shape_hash: __sdk::__query_builder::Col::new(table_name, "shape_hash"),
            policy_revision: __sdk::__query_builder::Col::new(table_name, "policy_revision"),
            last_plan_step: __sdk::__query_builder::Col::new(table_name, "last_plan_step"),
        }
    }
}

/// Indexed column accessor struct for the table `PolicyReplanState`.
///
/// Provides typed access to indexed columns for query building.
pub struct PolicyReplanStateIxCols {
    pub component_key: __sdk::__query_builder::IxCol<PolicyReplanState, u64>,
}

impl __sdk::__query_builder::HasIxCols for PolicyReplanState {
    type IxCols = PolicyReplanStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PolicyReplanStateIxCols {
            component_key: __sdk::__query_builder::IxCol::new(table_name, "component_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PolicyReplanState {}
