// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::terrain_class_type::TerrainClass;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PolicyTopologyCache {
    pub component_key: u64,
    pub owner_player_id: u8,
    pub ownership_revision: u64,
    pub shape_hash: u64,
    pub cell_ids: Vec<u32>,
    pub q: Vec<i32>,
    pub r: Vec<i32>,
    pub terrain: Vec<TerrainClass>,
    pub elevation: Vec<i16>,
    pub capturable: Vec<bool>,
    pub habitable: Vec<bool>,
    pub civilian_capacity: Vec<u64>,
    pub military_capacity: Vec<u64>,
    pub core_weights: Vec<u32>,
}

impl __sdk::InModule for PolicyTopologyCache {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PolicyTopologyCache`.
///
/// Provides typed access to columns for query building.
pub struct PolicyTopologyCacheCols {
    pub component_key: __sdk::__query_builder::Col<PolicyTopologyCache, u64>,
    pub owner_player_id: __sdk::__query_builder::Col<PolicyTopologyCache, u8>,
    pub ownership_revision: __sdk::__query_builder::Col<PolicyTopologyCache, u64>,
    pub shape_hash: __sdk::__query_builder::Col<PolicyTopologyCache, u64>,
    pub cell_ids: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<u32>>,
    pub q: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<i32>>,
    pub r: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<i32>>,
    pub terrain: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<TerrainClass>>,
    pub elevation: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<i16>>,
    pub capturable: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<bool>>,
    pub habitable: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<bool>>,
    pub civilian_capacity: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<u64>>,
    pub military_capacity: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<u64>>,
    pub core_weights: __sdk::__query_builder::Col<PolicyTopologyCache, Vec<u32>>,
}

impl __sdk::__query_builder::HasCols for PolicyTopologyCache {
    type Cols = PolicyTopologyCacheCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PolicyTopologyCacheCols {
            component_key: __sdk::__query_builder::Col::new(table_name, "component_key"),
            owner_player_id: __sdk::__query_builder::Col::new(table_name, "owner_player_id"),
            ownership_revision: __sdk::__query_builder::Col::new(table_name, "ownership_revision"),
            shape_hash: __sdk::__query_builder::Col::new(table_name, "shape_hash"),
            cell_ids: __sdk::__query_builder::Col::new(table_name, "cell_ids"),
            q: __sdk::__query_builder::Col::new(table_name, "q"),
            r: __sdk::__query_builder::Col::new(table_name, "r"),
            terrain: __sdk::__query_builder::Col::new(table_name, "terrain"),
            elevation: __sdk::__query_builder::Col::new(table_name, "elevation"),
            capturable: __sdk::__query_builder::Col::new(table_name, "capturable"),
            habitable: __sdk::__query_builder::Col::new(table_name, "habitable"),
            civilian_capacity: __sdk::__query_builder::Col::new(table_name, "civilian_capacity"),
            military_capacity: __sdk::__query_builder::Col::new(table_name, "military_capacity"),
            core_weights: __sdk::__query_builder::Col::new(table_name, "core_weights"),
        }
    }
}

/// Indexed column accessor struct for the table `PolicyTopologyCache`.
///
/// Provides typed access to indexed columns for query building.
pub struct PolicyTopologyCacheIxCols {
    pub component_key: __sdk::__query_builder::IxCol<PolicyTopologyCache, u64>,
}

impl __sdk::__query_builder::HasIxCols for PolicyTopologyCache {
    type IxCols = PolicyTopologyCacheIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PolicyTopologyCacheIxCols {
            component_key: __sdk::__query_builder::IxCol::new(table_name, "component_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PolicyTopologyCache {}
