// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RetreatAbandonment {
    pub abandonment_key: u128,
    pub order_id: u64,
    pub cell_id: u32,
}

impl __sdk::InModule for RetreatAbandonment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RetreatAbandonment`.
///
/// Provides typed access to columns for query building.
pub struct RetreatAbandonmentCols {
    pub abandonment_key: __sdk::__query_builder::Col<RetreatAbandonment, u128>,
    pub order_id: __sdk::__query_builder::Col<RetreatAbandonment, u64>,
    pub cell_id: __sdk::__query_builder::Col<RetreatAbandonment, u32>,
}

impl __sdk::__query_builder::HasCols for RetreatAbandonment {
    type Cols = RetreatAbandonmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RetreatAbandonmentCols {
            abandonment_key: __sdk::__query_builder::Col::new(table_name, "abandonment_key"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
        }
    }
}

/// Indexed column accessor struct for the table `RetreatAbandonment`.
///
/// Provides typed access to indexed columns for query building.
pub struct RetreatAbandonmentIxCols {
    pub abandonment_key: __sdk::__query_builder::IxCol<RetreatAbandonment, u128>,
    pub order_id: __sdk::__query_builder::IxCol<RetreatAbandonment, u64>,
}

impl __sdk::__query_builder::HasIxCols for RetreatAbandonment {
    type IxCols = RetreatAbandonmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RetreatAbandonmentIxCols {
            abandonment_key: __sdk::__query_builder::IxCol::new(table_name, "abandonment_key"),
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RetreatAbandonment {}
