// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetMobilizationTargetArgs {
    pub client_command_id: u64,
    pub target_bps: u32,
}

impl From<SetMobilizationTargetArgs> for super::Reducer {
    fn from(args: SetMobilizationTargetArgs) -> Self {
        Self::SetMobilizationTarget {
            client_command_id: args.client_command_id,
            target_bps: args.target_bps,
        }
    }
}

impl __sdk::InModule for SetMobilizationTargetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_mobilization_target`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_mobilization_target {
    /// Request that the remote module invoke the reducer `set_mobilization_target` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_mobilization_target:set_mobilization_target_then`] to run a callback after the reducer completes.
    fn set_mobilization_target(
        &self,
        client_command_id: u64,
        target_bps: u32,
    ) -> __sdk::Result<()> {
        self.set_mobilization_target_then(client_command_id, target_bps, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_mobilization_target` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_mobilization_target_then(
        &self,
        client_command_id: u64,
        target_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_mobilization_target for super::RemoteReducers {
    fn set_mobilization_target_then(
        &self,
        client_command_id: u64,
        target_bps: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetMobilizationTargetArgs {
                client_command_id,
                target_bps,
            },
            callback,
        )
    }
}
