// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct StaticEdgeLimit {
    pub edge_key: u64,
    pub first_cell: u32,
    pub second_cell: u32,
    pub traversable: bool,
    pub first_to_second_throughput: u64,
    pub second_to_first_throughput: u64,
    pub first_to_second_frontage: u64,
    pub second_to_first_frontage: u64,
    pub first_to_second_uphill: bool,
    pub second_to_first_uphill: bool,
}

impl __sdk::InModule for StaticEdgeLimit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `StaticEdgeLimit`.
///
/// Provides typed access to columns for query building.
pub struct StaticEdgeLimitCols {
    pub edge_key: __sdk::__query_builder::Col<StaticEdgeLimit, u64>,
    pub first_cell: __sdk::__query_builder::Col<StaticEdgeLimit, u32>,
    pub second_cell: __sdk::__query_builder::Col<StaticEdgeLimit, u32>,
    pub traversable: __sdk::__query_builder::Col<StaticEdgeLimit, bool>,
    pub first_to_second_throughput: __sdk::__query_builder::Col<StaticEdgeLimit, u64>,
    pub second_to_first_throughput: __sdk::__query_builder::Col<StaticEdgeLimit, u64>,
    pub first_to_second_frontage: __sdk::__query_builder::Col<StaticEdgeLimit, u64>,
    pub second_to_first_frontage: __sdk::__query_builder::Col<StaticEdgeLimit, u64>,
    pub first_to_second_uphill: __sdk::__query_builder::Col<StaticEdgeLimit, bool>,
    pub second_to_first_uphill: __sdk::__query_builder::Col<StaticEdgeLimit, bool>,
}

impl __sdk::__query_builder::HasCols for StaticEdgeLimit {
    type Cols = StaticEdgeLimitCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        StaticEdgeLimitCols {
            edge_key: __sdk::__query_builder::Col::new(table_name, "edge_key"),
            first_cell: __sdk::__query_builder::Col::new(table_name, "first_cell"),
            second_cell: __sdk::__query_builder::Col::new(table_name, "second_cell"),
            traversable: __sdk::__query_builder::Col::new(table_name, "traversable"),
            first_to_second_throughput: __sdk::__query_builder::Col::new(
                table_name,
                "first_to_second_throughput",
            ),
            second_to_first_throughput: __sdk::__query_builder::Col::new(
                table_name,
                "second_to_first_throughput",
            ),
            first_to_second_frontage: __sdk::__query_builder::Col::new(
                table_name,
                "first_to_second_frontage",
            ),
            second_to_first_frontage: __sdk::__query_builder::Col::new(
                table_name,
                "second_to_first_frontage",
            ),
            first_to_second_uphill: __sdk::__query_builder::Col::new(
                table_name,
                "first_to_second_uphill",
            ),
            second_to_first_uphill: __sdk::__query_builder::Col::new(
                table_name,
                "second_to_first_uphill",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `StaticEdgeLimit`.
///
/// Provides typed access to indexed columns for query building.
pub struct StaticEdgeLimitIxCols {
    pub edge_key: __sdk::__query_builder::IxCol<StaticEdgeLimit, u64>,
}

impl __sdk::__query_builder::HasIxCols for StaticEdgeLimit {
    type IxCols = StaticEdgeLimitIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        StaticEdgeLimitIxCols {
            edge_key: __sdk::__query_builder::IxCol::new(table_name, "edge_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for StaticEdgeLimit {}
