// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TransitRoute {
    pub route_id: u64,
    pub order_id: u64,
    pub player_id: u16,
    pub cells: Vec<u32>,
}

impl __sdk::InModule for TransitRoute {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TransitRoute`.
///
/// Provides typed access to columns for query building.
pub struct TransitRouteCols {
    pub route_id: __sdk::__query_builder::Col<TransitRoute, u64>,
    pub order_id: __sdk::__query_builder::Col<TransitRoute, u64>,
    pub player_id: __sdk::__query_builder::Col<TransitRoute, u16>,
    pub cells: __sdk::__query_builder::Col<TransitRoute, Vec<u32>>,
}

impl __sdk::__query_builder::HasCols for TransitRoute {
    type Cols = TransitRouteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransitRouteCols {
            route_id: __sdk::__query_builder::Col::new(table_name, "route_id"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            cells: __sdk::__query_builder::Col::new(table_name, "cells"),
        }
    }
}

/// Indexed column accessor struct for the table `TransitRoute`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransitRouteIxCols {
    pub order_id: __sdk::__query_builder::IxCol<TransitRoute, u64>,
    pub player_id: __sdk::__query_builder::IxCol<TransitRoute, u16>,
    pub route_id: __sdk::__query_builder::IxCol<TransitRoute, u64>,
}

impl __sdk::__query_builder::HasIxCols for TransitRoute {
    type IxCols = TransitRouteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransitRouteIxCols {
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            route_id: __sdk::__query_builder::IxCol::new(table_name, "route_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TransitRoute {}
