// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transfer_destination_type::TransferDestination;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transfer_destination`.
///
/// Obtain a handle from the [`TransferDestinationTableAccess::transfer_destination`] method on [`super::RemoteTables`],
/// like `ctx.db.transfer_destination()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_destination().on_insert(...)`.
pub struct TransferDestinationTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransferDestination>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `transfer_destination`.
pub struct TransferDestinationTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TransferDestinationTableAccessor {
    type Row = TransferDestination;
    type Handle<'db> = TransferDestinationTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.transfer_destination()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transfer_destination`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransferDestinationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransferDestinationTableHandle`], which mediates access to the table `transfer_destination`.
    fn transfer_destination(&self) -> TransferDestinationTableHandle<'_>;
}

impl TransferDestinationTableAccess for super::RemoteTables {
    fn transfer_destination(&self) -> TransferDestinationTableHandle<'_> {
        TransferDestinationTableHandle {
            imp: self
                .imp
                .get_table::<TransferDestination>("transfer_destination"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransferDestinationInsertCallbackId(__sdk::CallbackId);
pub struct TransferDestinationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TransferDestinationTableHandle<'ctx> {
    type Row = TransferDestination;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferDestination> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TransferDestinationTableHandle<'ctx> {
    type Row = TransferDestination;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferDestination> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransferDestinationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferDestinationInsertCallbackId {
        TransferDestinationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferDestinationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransferDestinationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferDestinationDeleteCallbackId {
        TransferDestinationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferDestinationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TransferDestinationTableHandle<'ctx> {
    type InsertCallbackId = TransferDestinationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferDestinationInsertCallbackId {
        TransferDestinationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferDestinationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TransferDestinationTableHandle<'ctx> {
    type DeleteCallbackId = TransferDestinationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferDestinationDeleteCallbackId {
        TransferDestinationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferDestinationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransferDestinationUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransferDestinationTableHandle<'ctx> {
    type UpdateCallbackId = TransferDestinationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferDestinationUpdateCallbackId {
        TransferDestinationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferDestinationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TransferDestinationTableHandle<'ctx> {
    type UpdateCallbackId = TransferDestinationUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferDestinationUpdateCallbackId {
        TransferDestinationUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferDestinationUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `destination_key` unique index on the table `transfer_destination`,
/// which allows point queries on the field of the same name
/// via the [`TransferDestinationDestinationKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_destination().destination_key().find(...)`.
pub struct TransferDestinationDestinationKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransferDestination, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransferDestinationTableHandle<'ctx> {
    /// Get a handle on the `destination_key` unique index on the table `transfer_destination`.
    pub fn destination_key(&self) -> TransferDestinationDestinationKeyUnique<'ctx> {
        TransferDestinationDestinationKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("destination_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransferDestinationDestinationKeyUnique<'ctx> {
    /// Find the subscribed row whose `destination_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TransferDestination> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransferDestination>("transfer_destination");
    _table.add_unique_constraint::<String>("destination_key", |row| &row.destination_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransferDestination>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransferDestination>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransferDestination`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait transfer_destinationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransferDestination`.
    fn transfer_destination(&self) -> __sdk::__query_builder::Table<TransferDestination>;
}

impl transfer_destinationQueryTableAccess for __sdk::QueryTableAccessor {
    fn transfer_destination(&self) -> __sdk::__query_builder::Table<TransferDestination> {
        __sdk::__query_builder::Table::new("transfer_destination")
    }
}
