// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transfer_source_type::TransferSource;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transfer_source`.
///
/// Obtain a handle from the [`TransferSourceTableAccess::transfer_source`] method on [`super::RemoteTables`],
/// like `ctx.db.transfer_source()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_source().on_insert(...)`.
pub struct TransferSourceTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransferSource>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `transfer_source`.
pub struct TransferSourceTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TransferSourceTableAccessor {
    type Row = TransferSource;
    type Handle<'db> = TransferSourceTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.transfer_source()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transfer_source`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransferSourceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransferSourceTableHandle`], which mediates access to the table `transfer_source`.
    fn transfer_source(&self) -> TransferSourceTableHandle<'_>;
}

impl TransferSourceTableAccess for super::RemoteTables {
    fn transfer_source(&self) -> TransferSourceTableHandle<'_> {
        TransferSourceTableHandle {
            imp: self.imp.get_table::<TransferSource>("transfer_source"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransferSourceInsertCallbackId(__sdk::CallbackId);
pub struct TransferSourceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TransferSourceTableHandle<'ctx> {
    type Row = TransferSource;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferSource> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TransferSourceTableHandle<'ctx> {
    type Row = TransferSource;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferSource> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransferSourceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferSourceInsertCallbackId {
        TransferSourceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferSourceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransferSourceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferSourceDeleteCallbackId {
        TransferSourceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferSourceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TransferSourceTableHandle<'ctx> {
    type InsertCallbackId = TransferSourceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferSourceInsertCallbackId {
        TransferSourceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferSourceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TransferSourceTableHandle<'ctx> {
    type DeleteCallbackId = TransferSourceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferSourceDeleteCallbackId {
        TransferSourceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferSourceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransferSourceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransferSourceTableHandle<'ctx> {
    type UpdateCallbackId = TransferSourceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferSourceUpdateCallbackId {
        TransferSourceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferSourceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TransferSourceTableHandle<'ctx> {
    type UpdateCallbackId = TransferSourceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferSourceUpdateCallbackId {
        TransferSourceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferSourceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `source_key` unique index on the table `transfer_source`,
/// which allows point queries on the field of the same name
/// via the [`TransferSourceSourceKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_source().source_key().find(...)`.
pub struct TransferSourceSourceKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransferSource, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransferSourceTableHandle<'ctx> {
    /// Get a handle on the `source_key` unique index on the table `transfer_source`.
    pub fn source_key(&self) -> TransferSourceSourceKeyUnique<'ctx> {
        TransferSourceSourceKeyUnique {
            imp: self.imp.get_unique_constraint::<u128>("source_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransferSourceSourceKeyUnique<'ctx> {
    /// Find the subscribed row whose `source_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<TransferSource> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransferSource>("transfer_source");
    _table.add_unique_constraint::<u128>("source_key", |row| &row.source_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransferSource>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransferSource>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransferSource`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait transfer_sourceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransferSource`.
    fn transfer_source(&self) -> __sdk::__query_builder::Table<TransferSource>;
}

impl transfer_sourceQueryTableAccess for __sdk::QueryTableAccessor {
    fn transfer_source(&self) -> __sdk::__query_builder::Table<TransferSource> {
        __sdk::__query_builder::Table::new("transfer_source")
    }
}
