// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::order_kind_type::OrderKind;
use super::order_status_type::OrderStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TransferOrder {
    pub order_id: u64,
    pub player_id: u8,
    pub client_command_id: u64,
    pub kind: OrderKind,
    pub status: OrderStatus,
    pub requested_infantry: u64,
    pub committed_infantry: u64,
    pub in_transit_infantry: u64,
    pub delivered_infantry: u64,
    pub casualty_infantry: u64,
    pub orientation_q: i32,
    pub orientation_r: i32,
    pub created_step: u64,
    pub updated_step: u64,
}

impl __sdk::InModule for TransferOrder {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TransferOrder`.
///
/// Provides typed access to columns for query building.
pub struct TransferOrderCols {
    pub order_id: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub player_id: __sdk::__query_builder::Col<TransferOrder, u8>,
    pub client_command_id: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub kind: __sdk::__query_builder::Col<TransferOrder, OrderKind>,
    pub status: __sdk::__query_builder::Col<TransferOrder, OrderStatus>,
    pub requested_infantry: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub committed_infantry: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub in_transit_infantry: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub delivered_infantry: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub casualty_infantry: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub orientation_q: __sdk::__query_builder::Col<TransferOrder, i32>,
    pub orientation_r: __sdk::__query_builder::Col<TransferOrder, i32>,
    pub created_step: __sdk::__query_builder::Col<TransferOrder, u64>,
    pub updated_step: __sdk::__query_builder::Col<TransferOrder, u64>,
}

impl __sdk::__query_builder::HasCols for TransferOrder {
    type Cols = TransferOrderCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransferOrderCols {
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            client_command_id: __sdk::__query_builder::Col::new(table_name, "client_command_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            requested_infantry: __sdk::__query_builder::Col::new(table_name, "requested_infantry"),
            committed_infantry: __sdk::__query_builder::Col::new(table_name, "committed_infantry"),
            in_transit_infantry: __sdk::__query_builder::Col::new(
                table_name,
                "in_transit_infantry",
            ),
            delivered_infantry: __sdk::__query_builder::Col::new(table_name, "delivered_infantry"),
            casualty_infantry: __sdk::__query_builder::Col::new(table_name, "casualty_infantry"),
            orientation_q: __sdk::__query_builder::Col::new(table_name, "orientation_q"),
            orientation_r: __sdk::__query_builder::Col::new(table_name, "orientation_r"),
            created_step: __sdk::__query_builder::Col::new(table_name, "created_step"),
            updated_step: __sdk::__query_builder::Col::new(table_name, "updated_step"),
        }
    }
}

/// Indexed column accessor struct for the table `TransferOrder`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransferOrderIxCols {
    pub order_id: __sdk::__query_builder::IxCol<TransferOrder, u64>,
    pub player_id: __sdk::__query_builder::IxCol<TransferOrder, u8>,
    pub status: __sdk::__query_builder::IxCol<TransferOrder, OrderStatus>,
}

impl __sdk::__query_builder::HasIxCols for TransferOrder {
    type IxCols = TransferOrderIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransferOrderIxCols {
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TransferOrder {}
