// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transit_packet_type::TransitPacket;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transit_packet`.
///
/// Obtain a handle from the [`TransitPacketTableAccess::transit_packet`] method on [`super::RemoteTables`],
/// like `ctx.db.transit_packet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transit_packet().on_insert(...)`.
pub struct TransitPacketTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransitPacket>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `transit_packet`.
pub struct TransitPacketTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TransitPacketTableAccessor {
    type Row = TransitPacket;
    type Handle<'db> = TransitPacketTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.transit_packet()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transit_packet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransitPacketTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransitPacketTableHandle`], which mediates access to the table `transit_packet`.
    fn transit_packet(&self) -> TransitPacketTableHandle<'_>;
}

impl TransitPacketTableAccess for super::RemoteTables {
    fn transit_packet(&self) -> TransitPacketTableHandle<'_> {
        TransitPacketTableHandle {
            imp: self.imp.get_table::<TransitPacket>("transit_packet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransitPacketInsertCallbackId(__sdk::CallbackId);
pub struct TransitPacketDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TransitPacketTableHandle<'ctx> {
    type Row = TransitPacket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitPacket> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TransitPacketTableHandle<'ctx> {
    type Row = TransitPacket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitPacket> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransitPacketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitPacketInsertCallbackId {
        TransitPacketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransitPacketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransitPacketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitPacketDeleteCallbackId {
        TransitPacketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransitPacketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TransitPacketTableHandle<'ctx> {
    type InsertCallbackId = TransitPacketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitPacketInsertCallbackId {
        TransitPacketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransitPacketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TransitPacketTableHandle<'ctx> {
    type DeleteCallbackId = TransitPacketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitPacketDeleteCallbackId {
        TransitPacketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransitPacketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransitPacketUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransitPacketTableHandle<'ctx> {
    type UpdateCallbackId = TransitPacketUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransitPacketUpdateCallbackId {
        TransitPacketUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransitPacketUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TransitPacketTableHandle<'ctx> {
    type UpdateCallbackId = TransitPacketUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransitPacketUpdateCallbackId {
        TransitPacketUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransitPacketUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `packet_key` unique index on the table `transit_packet`,
/// which allows point queries on the field of the same name
/// via the [`TransitPacketPacketKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transit_packet().packet_key().find(...)`.
pub struct TransitPacketPacketKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransitPacket, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransitPacketTableHandle<'ctx> {
    /// Get a handle on the `packet_key` unique index on the table `transit_packet`.
    pub fn packet_key(&self) -> TransitPacketPacketKeyUnique<'ctx> {
        TransitPacketPacketKeyUnique {
            imp: self.imp.get_unique_constraint::<u64>("packet_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransitPacketPacketKeyUnique<'ctx> {
    /// Find the subscribed row whose `packet_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TransitPacket> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransitPacket>("transit_packet");
    _table.add_unique_constraint::<u64>("packet_key", |row| &row.packet_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransitPacket>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransitPacket>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransitPacket`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait transit_packetQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransitPacket`.
    fn transit_packet(&self) -> __sdk::__query_builder::Table<TransitPacket>;
}

impl transit_packetQueryTableAccess for __sdk::QueryTableAccessor {
    fn transit_packet(&self) -> __sdk::__query_builder::Table<TransitPacket> {
        __sdk::__query_builder::Table::new("transit_packet")
    }
}
