// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TransferSource {
    pub source_key: String,
    pub order_id: u64,
    pub cell_id: u32,
    pub committed_infantry: u64,
    pub queued_infantry: u64,
}

impl __sdk::InModule for TransferSource {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TransferSource`.
///
/// Provides typed access to columns for query building.
pub struct TransferSourceCols {
    pub source_key: __sdk::__query_builder::Col<TransferSource, String>,
    pub order_id: __sdk::__query_builder::Col<TransferSource, u64>,
    pub cell_id: __sdk::__query_builder::Col<TransferSource, u32>,
    pub committed_infantry: __sdk::__query_builder::Col<TransferSource, u64>,
    pub queued_infantry: __sdk::__query_builder::Col<TransferSource, u64>,
}

impl __sdk::__query_builder::HasCols for TransferSource {
    type Cols = TransferSourceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransferSourceCols {
            source_key: __sdk::__query_builder::Col::new(table_name, "source_key"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            committed_infantry: __sdk::__query_builder::Col::new(table_name, "committed_infantry"),
            queued_infantry: __sdk::__query_builder::Col::new(table_name, "queued_infantry"),
        }
    }
}

/// Indexed column accessor struct for the table `TransferSource`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransferSourceIxCols {
    pub order_id: __sdk::__query_builder::IxCol<TransferSource, u64>,
    pub source_key: __sdk::__query_builder::IxCol<TransferSource, String>,
}

impl __sdk::__query_builder::HasIxCols for TransferSource {
    type IxCols = TransferSourceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransferSourceIxCols {
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
            source_key: __sdk::__query_builder::IxCol::new(table_name, "source_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TransferSource {}
