// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::order_kind_type::OrderKind;
use super::order_status_type::OrderStatus;
use super::transfer_order_type::TransferOrder;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transfer_order`.
///
/// Obtain a handle from the [`TransferOrderTableAccess::transfer_order`] method on [`super::RemoteTables`],
/// like `ctx.db.transfer_order()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_order().on_insert(...)`.
pub struct TransferOrderTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransferOrder>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `transfer_order`.
pub struct TransferOrderTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TransferOrderTableAccessor {
    type Row = TransferOrder;
    type Handle<'db> = TransferOrderTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.transfer_order()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transfer_order`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransferOrderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransferOrderTableHandle`], which mediates access to the table `transfer_order`.
    fn transfer_order(&self) -> TransferOrderTableHandle<'_>;
}

impl TransferOrderTableAccess for super::RemoteTables {
    fn transfer_order(&self) -> TransferOrderTableHandle<'_> {
        TransferOrderTableHandle {
            imp: self.imp.get_table::<TransferOrder>("transfer_order"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransferOrderInsertCallbackId(__sdk::CallbackId);
pub struct TransferOrderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TransferOrderTableHandle<'ctx> {
    type Row = TransferOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferOrder> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TransferOrderTableHandle<'ctx> {
    type Row = TransferOrder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransferOrder> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransferOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferOrderInsertCallbackId {
        TransferOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransferOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferOrderDeleteCallbackId {
        TransferOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TransferOrderTableHandle<'ctx> {
    type InsertCallbackId = TransferOrderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferOrderInsertCallbackId {
        TransferOrderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransferOrderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TransferOrderTableHandle<'ctx> {
    type DeleteCallbackId = TransferOrderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransferOrderDeleteCallbackId {
        TransferOrderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransferOrderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransferOrderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransferOrderTableHandle<'ctx> {
    type UpdateCallbackId = TransferOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferOrderUpdateCallbackId {
        TransferOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TransferOrderTableHandle<'ctx> {
    type UpdateCallbackId = TransferOrderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransferOrderUpdateCallbackId {
        TransferOrderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransferOrderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `order_id` unique index on the table `transfer_order`,
/// which allows point queries on the field of the same name
/// via the [`TransferOrderOrderIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transfer_order().order_id().find(...)`.
pub struct TransferOrderOrderIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransferOrder, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransferOrderTableHandle<'ctx> {
    /// Get a handle on the `order_id` unique index on the table `transfer_order`.
    pub fn order_id(&self) -> TransferOrderOrderIdUnique<'ctx> {
        TransferOrderOrderIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("order_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransferOrderOrderIdUnique<'ctx> {
    /// Find the subscribed row whose `order_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TransferOrder> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransferOrder>("transfer_order");
    _table.add_unique_constraint::<u64>("order_id", |row| &row.order_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransferOrder>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransferOrder>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransferOrder`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait transfer_orderQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransferOrder`.
    fn transfer_order(&self) -> __sdk::__query_builder::Table<TransferOrder>;
}

impl transfer_orderQueryTableAccess for __sdk::QueryTableAccessor {
    fn transfer_order(&self) -> __sdk::__query_builder::Table<TransferOrder> {
        __sdk::__query_builder::Table::new("transfer_order")
    }
}
