// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transit_route_type::TransitRoute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `transit_route`.
///
/// Obtain a handle from the [`TransitRouteTableAccess::transit_route`] method on [`super::RemoteTables`],
/// like `ctx.db.transit_route()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transit_route().on_insert(...)`.
pub struct TransitRouteTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransitRoute>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `transit_route`.
pub struct TransitRouteTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TransitRouteTableAccessor {
    type Row = TransitRoute;
    type Handle<'db> = TransitRouteTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.transit_route()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `transit_route`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TransitRouteTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TransitRouteTableHandle`], which mediates access to the table `transit_route`.
    fn transit_route(&self) -> TransitRouteTableHandle<'_>;
}

impl TransitRouteTableAccess for super::RemoteTables {
    fn transit_route(&self) -> TransitRouteTableHandle<'_> {
        TransitRouteTableHandle {
            imp: self.imp.get_table::<TransitRoute>("transit_route"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TransitRouteInsertCallbackId(__sdk::CallbackId);
pub struct TransitRouteDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TransitRouteTableHandle<'ctx> {
    type Row = TransitRoute;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitRoute> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TransitRouteTableHandle<'ctx> {
    type Row = TransitRoute;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitRoute> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TransitRouteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitRouteInsertCallbackId {
        TransitRouteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransitRouteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TransitRouteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitRouteDeleteCallbackId {
        TransitRouteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransitRouteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TransitRouteTableHandle<'ctx> {
    type InsertCallbackId = TransitRouteInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitRouteInsertCallbackId {
        TransitRouteInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TransitRouteInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TransitRouteTableHandle<'ctx> {
    type DeleteCallbackId = TransitRouteDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TransitRouteDeleteCallbackId {
        TransitRouteDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TransitRouteDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TransitRouteUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TransitRouteTableHandle<'ctx> {
    type UpdateCallbackId = TransitRouteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransitRouteUpdateCallbackId {
        TransitRouteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransitRouteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TransitRouteTableHandle<'ctx> {
    type UpdateCallbackId = TransitRouteUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TransitRouteUpdateCallbackId {
        TransitRouteUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TransitRouteUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `route_id` unique index on the table `transit_route`,
/// which allows point queries on the field of the same name
/// via the [`TransitRouteRouteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.transit_route().route_id().find(...)`.
pub struct TransitRouteRouteIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransitRoute, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TransitRouteTableHandle<'ctx> {
    /// Get a handle on the `route_id` unique index on the table `transit_route`.
    pub fn route_id(&self) -> TransitRouteRouteIdUnique<'ctx> {
        TransitRouteRouteIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("route_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TransitRouteRouteIdUnique<'ctx> {
    /// Find the subscribed row whose `route_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TransitRoute> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransitRoute>("transit_route");
    _table.add_unique_constraint::<u64>("route_id", |row| &row.route_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransitRoute>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransitRoute>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransitRoute`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait transit_routeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransitRoute`.
    fn transit_route(&self) -> __sdk::__query_builder::Table<TransitRoute>;
}

impl transit_routeQueryTableAccess for __sdk::QueryTableAccessor {
    fn transit_route(&self) -> __sdk::__query_builder::Table<TransitRoute> {
        __sdk::__query_builder::Table::new("transit_route")
    }
}
