// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TransitPacket {
    pub packet_key: String,
    pub order_id: u64,
    pub owner_player_id: u8,
    pub origin_cell: u32,
    pub current_cell: u32,
    pub destination_cell: u32,
    pub infantry: u64,
    pub route_index: u32,
    pub route: Vec<u32>,
    pub updated_step: u64,
}

impl __sdk::InModule for TransitPacket {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TransitPacket`.
///
/// Provides typed access to columns for query building.
pub struct TransitPacketCols {
    pub packet_key: __sdk::__query_builder::Col<TransitPacket, String>,
    pub order_id: __sdk::__query_builder::Col<TransitPacket, u64>,
    pub owner_player_id: __sdk::__query_builder::Col<TransitPacket, u8>,
    pub origin_cell: __sdk::__query_builder::Col<TransitPacket, u32>,
    pub current_cell: __sdk::__query_builder::Col<TransitPacket, u32>,
    pub destination_cell: __sdk::__query_builder::Col<TransitPacket, u32>,
    pub infantry: __sdk::__query_builder::Col<TransitPacket, u64>,
    pub route_index: __sdk::__query_builder::Col<TransitPacket, u32>,
    pub route: __sdk::__query_builder::Col<TransitPacket, Vec<u32>>,
    pub updated_step: __sdk::__query_builder::Col<TransitPacket, u64>,
}

impl __sdk::__query_builder::HasCols for TransitPacket {
    type Cols = TransitPacketCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TransitPacketCols {
            packet_key: __sdk::__query_builder::Col::new(table_name, "packet_key"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            owner_player_id: __sdk::__query_builder::Col::new(table_name, "owner_player_id"),
            origin_cell: __sdk::__query_builder::Col::new(table_name, "origin_cell"),
            current_cell: __sdk::__query_builder::Col::new(table_name, "current_cell"),
            destination_cell: __sdk::__query_builder::Col::new(table_name, "destination_cell"),
            infantry: __sdk::__query_builder::Col::new(table_name, "infantry"),
            route_index: __sdk::__query_builder::Col::new(table_name, "route_index"),
            route: __sdk::__query_builder::Col::new(table_name, "route"),
            updated_step: __sdk::__query_builder::Col::new(table_name, "updated_step"),
        }
    }
}

/// Indexed column accessor struct for the table `TransitPacket`.
///
/// Provides typed access to indexed columns for query building.
pub struct TransitPacketIxCols {
    pub current_cell: __sdk::__query_builder::IxCol<TransitPacket, u32>,
    pub order_id: __sdk::__query_builder::IxCol<TransitPacket, u64>,
    pub packet_key: __sdk::__query_builder::IxCol<TransitPacket, String>,
}

impl __sdk::__query_builder::HasIxCols for TransitPacket {
    type IxCols = TransitPacketIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TransitPacketIxCols {
            current_cell: __sdk::__query_builder::IxCol::new(table_name, "current_cell"),
            order_id: __sdk::__query_builder::IxCol::new(table_name, "order_id"),
            packet_key: __sdk::__query_builder::IxCol::new(table_name, "packet_key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TransitPacket {}
