// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transit_packet_type::TransitPacket;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_packets`.
///
/// Obtain a handle from the [`VisiblePacketsTableAccess::visible_packets`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_packets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_packets().on_insert(...)`.
pub struct VisiblePacketsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransitPacket>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_packets`.
pub struct VisiblePacketsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisiblePacketsTableAccessor {
    type Row = TransitPacket;
    type Handle<'db> = VisiblePacketsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_packets()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_packets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisiblePacketsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisiblePacketsTableHandle`], which mediates access to the table `visible_packets`.
    fn visible_packets(&self) -> VisiblePacketsTableHandle<'_>;
}

impl VisiblePacketsTableAccess for super::RemoteTables {
    fn visible_packets(&self) -> VisiblePacketsTableHandle<'_> {
        VisiblePacketsTableHandle {
            imp: self.imp.get_table::<TransitPacket>("visible_packets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisiblePacketsInsertCallbackId(__sdk::CallbackId);
pub struct VisiblePacketsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisiblePacketsTableHandle<'ctx> {
    type Row = TransitPacket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitPacket> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisiblePacketsTableHandle<'ctx> {
    type Row = TransitPacket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitPacket> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisiblePacketsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsInsertCallbackId {
        VisiblePacketsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisiblePacketsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisiblePacketsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsDeleteCallbackId {
        VisiblePacketsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisiblePacketsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisiblePacketsTableHandle<'ctx> {
    type InsertCallbackId = VisiblePacketsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsInsertCallbackId {
        VisiblePacketsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisiblePacketsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisiblePacketsTableHandle<'ctx> {
    type DeleteCallbackId = VisiblePacketsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsDeleteCallbackId {
        VisiblePacketsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisiblePacketsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisiblePacketsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisiblePacketsTableHandle<'ctx> {
    type UpdateCallbackId = VisiblePacketsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsUpdateCallbackId {
        VisiblePacketsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisiblePacketsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisiblePacketsTableHandle<'ctx> {
    type UpdateCallbackId = VisiblePacketsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisiblePacketsUpdateCallbackId {
        VisiblePacketsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisiblePacketsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `packet_key` unique index on the table `visible_packets`,
/// which allows point queries on the field of the same name
/// via the [`VisiblePacketsPacketKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_packets().packet_key().find(...)`.
pub struct VisiblePacketsPacketKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransitPacket, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisiblePacketsTableHandle<'ctx> {
    /// Get a handle on the `packet_key` unique index on the table `visible_packets`.
    pub fn packet_key(&self) -> VisiblePacketsPacketKeyUnique<'ctx> {
        VisiblePacketsPacketKeyUnique {
            imp: self.imp.get_unique_constraint::<String>("packet_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisiblePacketsPacketKeyUnique<'ctx> {
    /// Find the subscribed row whose `packet_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TransitPacket> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransitPacket>("visible_packets");
    _table.add_unique_constraint::<String>("packet_key", |row| &row.packet_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransitPacket>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransitPacket>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransitPacket`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_packetsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransitPacket`.
    fn visible_packets(&self) -> __sdk::__query_builder::Table<TransitPacket>;
}

impl visible_packetsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_packets(&self) -> __sdk::__query_builder::Table<TransitPacket> {
        __sdk::__query_builder::Table::new("visible_packets")
    }
}
