// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transit_route_type::TransitRoute;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_routes`.
///
/// Obtain a handle from the [`VisibleRoutesTableAccess::visible_routes`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_routes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_routes().on_insert(...)`.
pub struct VisibleRoutesTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransitRoute>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_routes`.
pub struct VisibleRoutesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleRoutesTableAccessor {
    type Row = TransitRoute;
    type Handle<'db> = VisibleRoutesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_routes()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_routes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleRoutesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleRoutesTableHandle`], which mediates access to the table `visible_routes`.
    fn visible_routes(&self) -> VisibleRoutesTableHandle<'_>;
}

impl VisibleRoutesTableAccess for super::RemoteTables {
    fn visible_routes(&self) -> VisibleRoutesTableHandle<'_> {
        VisibleRoutesTableHandle {
            imp: self.imp.get_table::<TransitRoute>("visible_routes"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleRoutesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleRoutesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleRoutesTableHandle<'ctx> {
    type Row = TransitRoute;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitRoute> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleRoutesTableHandle<'ctx> {
    type Row = TransitRoute;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransitRoute> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleRoutesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesInsertCallbackId {
        VisibleRoutesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoutesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleRoutesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesDeleteCallbackId {
        VisibleRoutesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoutesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleRoutesTableHandle<'ctx> {
    type InsertCallbackId = VisibleRoutesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesInsertCallbackId {
        VisibleRoutesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleRoutesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleRoutesTableHandle<'ctx> {
    type DeleteCallbackId = VisibleRoutesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesDeleteCallbackId {
        VisibleRoutesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleRoutesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleRoutesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleRoutesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoutesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesUpdateCallbackId {
        VisibleRoutesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoutesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleRoutesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleRoutesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleRoutesUpdateCallbackId {
        VisibleRoutesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleRoutesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `route_id` unique index on the table `visible_routes`,
/// which allows point queries on the field of the same name
/// via the [`VisibleRoutesRouteIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_routes().route_id().find(...)`.
pub struct VisibleRoutesRouteIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TransitRoute, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleRoutesTableHandle<'ctx> {
    /// Get a handle on the `route_id` unique index on the table `visible_routes`.
    pub fn route_id(&self) -> VisibleRoutesRouteIdUnique<'ctx> {
        VisibleRoutesRouteIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("route_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleRoutesRouteIdUnique<'ctx> {
    /// Find the subscribed row whose `route_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TransitRoute> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransitRoute>("visible_routes");
    _table.add_unique_constraint::<u64>("route_id", |row| &row.route_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransitRoute>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransitRoute>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransitRoute`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_routesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransitRoute`.
    fn visible_routes(&self) -> __sdk::__query_builder::Table<TransitRoute>;
}

impl visible_routesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_routes(&self) -> __sdk::__query_builder::Table<TransitRoute> {
        __sdk::__query_builder::Table::new("visible_routes")
    }
}
