//! Machine-generated run artifact and results document.

use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use serde::Serialize;

use crate::monitor::MonitorReport;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub enum Verdict {
    Pass,
    Fail,
    Partial,
}

impl Verdict {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Pass => "PASS",
            Self::Fail => "FAIL",
            Self::Partial => "PARTIAL",
        }
    }
}

#[derive(Clone, Debug, Serialize)]
pub struct ScenarioResult {
    pub risk: String,
    pub title: String,
    pub verdict: Verdict,
    /// Concrete measured evidence lines (numbers, cell IDs, totals).
    pub evidence: Vec<String>,
    /// Known limitations of this automated staging, if any.
    pub limitations: Vec<String>,
}

impl ScenarioResult {
    pub fn new(risk: &str, title: &str) -> Self {
        Self {
            risk: risk.to_owned(),
            title: title.to_owned(),
            verdict: Verdict::Pass,
            evidence: Vec::new(),
            limitations: Vec::new(),
        }
    }

    pub fn note(&mut self, line: impl Into<String>) {
        self.evidence.push(line.into());
    }

    pub fn fail(&mut self, line: impl Into<String>) {
        self.verdict = Verdict::Fail;
        self.evidence.push(format!("FAILED: {}", line.into()));
    }

    pub fn limit(&mut self, line: impl Into<String>) {
        if self.verdict == Verdict::Pass {
            self.verdict = Verdict::Partial;
        }
        self.limitations.push(line.into());
    }
}

#[derive(Clone, Debug, Serialize)]
pub struct RunReport {
    pub kind: &'static str,
    pub host: String,
    pub database: String,
    pub map_preset: String,
    pub map_seed: u64,
    pub git_sha: String,
    pub started_unix_ms: u128,
    pub finished_unix_ms: u128,
    pub logical_step_ms: u32,
    pub scenarios: Vec<ScenarioResult>,
    pub monitor: MonitorReport,
    pub passed: bool,
}

pub fn unix_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .unwrap_or(0)
}

/// UTC calendar date (`YYYY-MM-DD`) for artifact naming, derived without a
/// date-time dependency (civil-from-days, Howard Hinnant's algorithm).
pub fn utc_date_label() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0);
    let days = i64::try_from(secs / 86_400).unwrap_or(0);
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { year + 1 } else { year };
    format!("{year:04}-{month:02}-{day:02}")
}

pub fn write_json(path: &Path, report: &RunReport) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create artifact directory {}", parent.display()))?;
    }
    let payload = serde_json::to_vec_pretty(report).context("serialize run report")?;
    fs::write(path, payload).with_context(|| format!("write run artifact {}", path.display()))?;
    Ok(())
}

#[allow(clippy::too_many_lines)]
pub fn write_markdown(path: &Path, report: &RunReport, date: &str) -> Result<()> {
    let mut doc = String::new();
    doc.push_str(&format!(
        "# Cluster controls V1 automated playtest — {date}\n\n"
    ));
    doc.push_str(
        "> Machine-generated by `cargo run -p match-playtest`. Every verdict below is\n\
         > **automated behavioral verification** against a real local SpacetimeDB match\n\
         > (assertions over the public reducer/table surface), **not** human-perception\n\
         > validation. Re-run the [manual checklist](./cluster-controls-v1.md) with\n\
         > participants for the perception rows.\n\n",
    );
    doc.push_str("## Session\n\n");
    doc.push_str("- Method: automated live two-player session (headless SDK clients + one invariant observer)\n");
    doc.push_str(&format!("- Git SHA: `{}`\n", report.git_sha));
    doc.push_str(&format!(
        "- Host / database: `{}` / `{}` (isolated; freshly published)\n",
        report.host, report.database
    ));
    doc.push_str(&format!(
        "- Map preset: `{}` (seed `{:#x}`), logical step {} ms\n",
        report.map_preset, report.map_seed, report.logical_step_ms
    ));
    doc.push_str(&format!(
        "- Wall time: {:.1} s; simulation steps observed: {}..{}\n",
        (report
            .finished_unix_ms
            .saturating_sub(report.started_unix_ms)) as f64
            / 1000.0,
        report.monitor.first_step,
        report.monitor.last_step
    ));
    doc.push_str(
        "- Raw artifact: `artifacts/playtests/` (gitignored JSON with all measurements)\n\n",
    );

    doc.push_str("## Results\n\n");
    doc.push_str("| Risk | Verdict | Automated behavioral evidence |\n");
    doc.push_str("| --- | --- | --- |\n");
    for scenario in &report.scenarios {
        let mut cell = scenario.evidence.join("<br>");
        if !scenario.limitations.is_empty() {
            cell.push_str("<br>Limitations: ");
            cell.push_str(&scenario.limitations.join("; "));
        }
        doc.push_str(&format!(
            "| {} | **{}** | {} |\n",
            scenario.title,
            scenario.verdict.label(),
            cell.replace('\n', " ")
        ));
    }

    doc.push_str("\n## Continuous global invariants\n\n");
    let monitor = &report.monitor;
    doc.push_str(&format!(
        "- Samples: {} ({} stable conservation checkpoints)\n",
        monitor.samples, monitor.stable_checkpoints
    ));
    doc.push_str(&format!(
        "- Tick liveness: logical_step advanced {} → {}\n",
        monitor.first_step, monitor.last_step
    ));
    doc.push_str(&format!(
        "- Physical traversal: {} forward route transitions observed, zero teleports/rewinds tolerated\n",
        monitor.tracked_packet_transitions
    ));
    doc.push_str(&format!(
        "- Peak cell fill ratio: {:.2}% of military capacity (no cell ever above 100%)\n",
        monitor.max_cell_fill_ratio_bps as f64 / 100.0
    ));
    for window in &monitor.windows {
        doc.push_str(&format!(
            "- {} window steps {}..{}: total infantry {} → {}, order-recorded (attacker) casualties {}, defender-side losses {}\n",
            window.mode,
            window.first_step,
            window.last_step,
            window.start_infantry,
            window.end_infantry,
            window.attacker_casualty_delta,
            window.defender_loss_residual
        ));
    }
    if monitor.violations.is_empty() {
        doc.push_str("- Violations: **none**\n");
    } else {
        doc.push_str(&format!(
            "- Violations: **{}** (real failures caught by instrumentation)\n",
            monitor.violations.len()
        ));
        for violation in &monitor.violations {
            doc.push_str(&format!(
                "  - `{}` at step {} ({:?} window): {}\n",
                violation.rule, violation.logical_step, violation.mode, violation.detail
            ));
        }
    }

    doc.push_str("\n## Overall\n\n");
    let fail_count = report
        .scenarios
        .iter()
        .filter(|scenario| scenario.verdict == Verdict::Fail)
        .count();
    let partial_count = report
        .scenarios
        .iter()
        .filter(|scenario| scenario.verdict == Verdict::Partial)
        .count();
    if report.passed && fail_count == 0 && partial_count == 0 {
        doc.push_str(
            "All six documented control risks verified behaviorally against the live \
             authoritative module, with continuous conservation, capacity, ownership, \
             traversal, and liveness instrumentation reporting no violations.\n",
        );
    } else if report.passed && fail_count == 0 {
        doc.push_str(&format!(
            "No automated behavioral check **FAILED** and the conservation monitor reported \
             no invariant violations. {partial_count} scenario(s) returned **PARTIAL** because \
             staging or sampling limits prevented a full proof on this map/run; see limitation \
             notes in the table above.\n",
        ));
    } else {
        doc.push_str(
            "At least one automated behavioral check FAILED or a global invariant was \
             violated; see the rows and violation list above. Failures are reported \
             faithfully and deserve investigation before the next milestone.\n",
        );
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create results directory {}", parent.display()))?;
    }
    fs::write(path, doc).with_context(|| format!("write results document {}", path.display()))?;
    Ok(())
}
